// City database and region mappings for WOPR globe
// (Continent outlines are in coastlines.js)

// Major world cities for targeting — ~400 cities with population (millions)
const CITIES = [
  // === NORTH AMERICA — US ===
  { name: "WASHINGTON DC", lat: 38.9, lon: -77.0, country: "US", region: "us", pop: 0.7 },
  { name: "NEW YORK", lat: 40.7, lon: -74.0, country: "US", region: "us", pop: 8.3 },
  { name: "LOS ANGELES", lat: 34.1, lon: -118.2, country: "US", region: "us", pop: 3.9 },
  { name: "CHICAGO", lat: 41.9, lon: -87.6, country: "US", region: "us", pop: 2.7 },
  { name: "HOUSTON", lat: 29.8, lon: -95.4, country: "US", region: "us", pop: 2.3 },
  { name: "PHOENIX", lat: 33.4, lon: -112.1, country: "US", region: "us", pop: 1.6 },
  { name: "PHILADELPHIA", lat: 40.0, lon: -75.2, country: "US", region: "us", pop: 1.6 },
  { name: "SAN ANTONIO", lat: 29.4, lon: -98.5, country: "US", region: "us", pop: 1.5 },
  { name: "SAN DIEGO", lat: 32.7, lon: -117.2, country: "US", region: "us", pop: 1.4 },
  { name: "DALLAS", lat: 32.8, lon: -96.8, country: "US", region: "us", pop: 1.3 },
  { name: "SEATTLE", lat: 47.6, lon: -122.3, country: "US", region: "us", pop: 0.7 },
  { name: "DENVER", lat: 39.7, lon: -105.0, country: "US", region: "us", pop: 0.7 },
  { name: "BOSTON", lat: 42.4, lon: -71.1, country: "US", region: "us", pop: 0.7 },
  { name: "ATLANTA", lat: 33.7, lon: -84.4, country: "US", region: "us", pop: 0.5 },
  { name: "MIAMI", lat: 25.8, lon: -80.2, country: "US", region: "us", pop: 0.5 },
  { name: "SAN FRANCISCO", lat: 37.8, lon: -122.4, country: "US", region: "us", pop: 0.9 },
  { name: "DETROIT", lat: 42.3, lon: -83.0, country: "US", region: "us", pop: 0.6 },
  { name: "MINNEAPOLIS", lat: 44.9, lon: -93.3, country: "US", region: "us", pop: 0.4 },
  { name: "ST LOUIS", lat: 38.6, lon: -90.2, country: "US", region: "us", pop: 0.3 },
  { name: "HONOLULU", lat: 21.3, lon: -157.8, country: "US", region: "hawaii", pop: 0.4 },
  { name: "ANCHORAGE", lat: 61.2, lon: -149.9, country: "US", region: "alaska", pop: 0.3 },
  // === NORTH AMERICA — OTHER ===
  { name: "OTTAWA", lat: 45.4, lon: -75.7, country: "CANADA", region: "canada", pop: 1.0 },
  { name: "TORONTO", lat: 43.7, lon: -79.4, country: "CANADA", region: "canada", pop: 2.7 },
  { name: "VANCOUVER", lat: 49.3, lon: -123.1, country: "CANADA", region: "canada", pop: 0.6 },
  { name: "MONTREAL", lat: 45.5, lon: -73.6, country: "CANADA", region: "canada", pop: 1.7 },
  { name: "MEXICO CITY", lat: 19.4, lon: -99.1, country: "MEXICO", region: "mexico", pop: 9.2 },
  { name: "GUADALAJARA", lat: 20.7, lon: -103.3, country: "MEXICO", region: "mexico", pop: 1.5 },
  { name: "MONTERREY", lat: 25.7, lon: -100.3, country: "MEXICO", region: "mexico", pop: 1.1 },
  { name: "HAVANA", lat: 23.1, lon: -82.4, country: "CUBA", region: "cuba", pop: 2.1 },
  { name: "MANAGUA", lat: 12.1, lon: -86.3, country: "NICARAGUA", region: "nicaragua", pop: 1.0 },
  { name: "KINGSTON", lat: 18.0, lon: -76.8, country: "JAMAICA", region: "jamaica", pop: 0.6 },
  { name: "GUATEMALA CITY", lat: 14.6, lon: -90.5, country: "GUATEMALA", region: "us", pop: 1.0 },
  { name: "PANAMA CITY", lat: 9.0, lon: -79.5, country: "PANAMA", region: "us", pop: 0.9 },
  { name: "SAN JOSE", lat: 9.9, lon: -84.1, country: "COSTA RICA", region: "us", pop: 0.3 },
  { name: "TEGUCIGALPA", lat: 14.1, lon: -87.2, country: "HONDURAS", region: "us", pop: 1.1 },
  { name: "SAN SALVADOR", lat: 13.7, lon: -89.2, country: "EL SALVADOR", region: "us", pop: 0.5 },
  { name: "PORT-AU-PRINCE", lat: 18.5, lon: -72.3, country: "HAITI", region: "us", pop: 1.1 },
  { name: "SANTO DOMINGO", lat: 18.5, lon: -69.9, country: "DOMINICAN REP", region: "us", pop: 1.0 },
  { name: "NASSAU", lat: 25.1, lon: -77.3, country: "BAHAMAS", region: "us", pop: 0.3 },
  // === SOUTH AMERICA ===
  { name: "BUENOS AIRES", lat: -34.6, lon: -58.4, country: "ARGENTINA", region: "argentina", pop: 3.1 },
  { name: "BRASILIA", lat: -15.8, lon: -47.9, country: "BRAZIL", region: "brazilian", pop: 3.0 },
  { name: "SAO PAULO", lat: -23.6, lon: -46.6, country: "BRAZIL", region: "brazilian", pop: 12.3 },
  { name: "RIO DE JANEIRO", lat: -22.9, lon: -43.2, country: "BRAZIL", region: "brazilian", pop: 6.7 },
  { name: "SANTIAGO", lat: -33.4, lon: -70.6, country: "CHILE", region: "chile", pop: 5.6 },
  { name: "CARACAS", lat: 10.5, lon: -66.9, country: "VENEZUELA", region: "venezuela", pop: 2.1 },
  { name: "BOGOTA", lat: 4.7, lon: -74.1, country: "COLOMBIA", region: "us", pop: 7.4 },
  { name: "LIMA", lat: -12.0, lon: -77.0, country: "PERU", region: "us", pop: 10.0 },
  { name: "QUITO", lat: -0.2, lon: -78.5, country: "ECUADOR", region: "us", pop: 1.8 },
  { name: "LA PAZ", lat: -16.5, lon: -68.2, country: "BOLIVIA", region: "us", pop: 0.9 },
  { name: "MONTEVIDEO", lat: -34.9, lon: -56.2, country: "URUGUAY", region: "argentina", pop: 1.4 },
  { name: "ASUNCION", lat: -25.3, lon: -57.6, country: "PARAGUAY", region: "argentina", pop: 0.5 },
  { name: "GEORGETOWN", lat: 6.8, lon: -58.2, country: "GUYANA", region: "us", pop: 0.2 },
  { name: "PARAMARIBO", lat: 5.9, lon: -55.2, country: "SURINAME", region: "us", pop: 0.2 },
  // === EUROPE — NATO ===
  { name: "LONDON", lat: 51.5, lon: -0.1, country: "UK", region: "english", pop: 9.0 },
  { name: "BIRMINGHAM", lat: 52.5, lon: -1.9, country: "UK", region: "english", pop: 1.1 },
  { name: "GLASGOW", lat: 55.9, lon: -4.3, country: "UK", region: "english", pop: 0.6 },
  { name: "PARIS", lat: 48.9, lon: 2.3, country: "FRANCE", region: "french", pop: 2.2 },
  { name: "MARSEILLE", lat: 43.3, lon: 5.4, country: "FRANCE", region: "french", pop: 0.9 },
  { name: "LYON", lat: 45.8, lon: 4.8, country: "FRANCE", region: "french", pop: 0.5 },
  { name: "BERLIN", lat: 52.5, lon: 13.4, country: "W.GERMANY", region: "nato", pop: 3.4 },
  { name: "HAMBURG", lat: 53.6, lon: 10.0, country: "W.GERMANY", region: "nato", pop: 1.8 },
  { name: "MUNICH", lat: 48.1, lon: 11.6, country: "W.GERMANY", region: "bavarian", pop: 1.5 },
  { name: "ROME", lat: 41.9, lon: 12.5, country: "ITALY", region: "italian", pop: 2.8 },
  { name: "MILAN", lat: 45.5, lon: 9.2, country: "ITALY", region: "italian", pop: 1.4 },
  { name: "NAPLES", lat: 40.9, lon: 14.3, country: "ITALY", region: "italian", pop: 1.0 },
  { name: "MADRID", lat: 40.4, lon: -3.7, country: "SPAIN", region: "nato", pop: 3.2 },
  { name: "BARCELONA", lat: 41.4, lon: 2.2, country: "SPAIN", region: "nato", pop: 1.6 },
  { name: "LISBON", lat: 38.7, lon: -9.1, country: "PORTUGAL", region: "portugal", pop: 0.5 },
  { name: "AMSTERDAM", lat: 52.4, lon: 4.9, country: "NETHERLANDS", region: "nato", pop: 0.9 },
  { name: "BRUSSELS", lat: 50.8, lon: 4.4, country: "BELGIUM", region: "nato", pop: 0.2 },
  { name: "COPENHAGEN", lat: 55.7, lon: 12.6, country: "DENMARK", region: "danish", pop: 0.6 },
  { name: "OSLO", lat: 59.9, lon: 10.8, country: "NORWAY", region: "nato", pop: 0.7 },
  { name: "STOCKHOLM", lat: 59.3, lon: 18.1, country: "SWEDEN", region: "nato", pop: 1.0 },
  { name: "HELSINKI", lat: 60.2, lon: 24.9, country: "FINLAND", region: "nato", pop: 0.7 },
  { name: "REYKJAVIK", lat: 64.1, lon: -21.9, country: "ICELAND", region: "iceland", pop: 0.1 },
  { name: "ISTANBUL", lat: 41.0, lon: 29.0, country: "TURKEY", region: "turkish", pop: 15.5 },
  { name: "ANKARA", lat: 39.9, lon: 32.9, country: "TURKEY", region: "turkish", pop: 5.7 },
  { name: "ATHENS", lat: 37.9, lon: 23.7, country: "GREECE", region: "nato", pop: 3.2 },
  { name: "BERN", lat: 46.9, lon: 7.4, country: "SWITZERLAND", region: "swiss", pop: 0.1 },
  { name: "VIENNA", lat: 48.2, lon: 16.4, country: "AUSTRIA", region: "nato", pop: 1.9 },
  { name: "DUBLIN", lat: 53.3, lon: -6.3, country: "IRELAND", region: "english", pop: 0.5 },
  { name: "NICOSIA", lat: 35.2, lon: 33.4, country: "CYPRUS", region: "cyprus", pop: 0.2 },
  { name: "LUXEMBOURG", lat: 49.6, lon: 6.1, country: "LUXEMBOURG", region: "nato", pop: 0.1 },
  // === EUROPE — WARSAW PACT ===
  { name: "MOSCOW", lat: 55.8, lon: 37.6, country: "USSR", region: "ussr", pop: 8.9 },
  { name: "LENINGRAD", lat: 59.9, lon: 30.3, country: "USSR", region: "ussr", pop: 5.0 },
  { name: "KIEV", lat: 50.5, lon: 30.5, country: "USSR", region: "ussr", pop: 2.6 },
  { name: "MINSK", lat: 53.9, lon: 27.6, country: "USSR", region: "ussr", pop: 1.7 },
  { name: "STALINGRAD", lat: 48.7, lon: 44.5, country: "USSR", region: "ussr", pop: 1.0 },
  { name: "SVERDLOVSK", lat: 56.8, lon: 60.6, country: "USSR", region: "ussr", pop: 1.3 },
  { name: "NOVOSIBIRSK", lat: 55.0, lon: 82.9, country: "USSR", region: "ussr", pop: 1.4 },
  { name: "GORKY", lat: 56.3, lon: 44.0, country: "USSR", region: "ussr", pop: 1.3 },
  { name: "TASHKENT", lat: 41.3, lon: 69.3, country: "USSR", region: "ussr", pop: 2.1 },
  { name: "MURMANSK", lat: 68.9, lon: 33.1, country: "USSR", region: "arctic", pop: 0.3 },
  { name: "VLADIVOSTOK", lat: 43.1, lon: 131.9, country: "USSR", region: "ussr", pop: 0.6 },
  { name: "ODESSA", lat: 46.5, lon: 30.7, country: "USSR", region: "ussr", pop: 1.0 },
  { name: "TBILISI", lat: 41.7, lon: 44.8, country: "USSR", region: "ussr", pop: 1.2 },
  { name: "BAKU", lat: 40.4, lon: 49.9, country: "USSR", region: "caspian", pop: 1.8 },
  { name: "RIGA", lat: 56.9, lon: 24.1, country: "USSR", region: "ussr", pop: 0.9 },
  { name: "ALMA-ATA", lat: 43.2, lon: 76.9, country: "USSR", region: "ussr", pop: 1.1 },
  { name: "WARSAW", lat: 52.2, lon: 21.0, country: "POLAND", region: "pact", pop: 1.7 },
  { name: "KRAKOW", lat: 50.1, lon: 19.9, country: "POLAND", region: "pact", pop: 0.7 },
  { name: "PRAGUE", lat: 50.1, lon: 14.4, country: "CZECHOSLOVAKIA", region: "czech", pop: 1.2 },
  { name: "BUCHAREST", lat: 44.4, lon: 26.1, country: "ROMANIA", region: "romanian", pop: 1.9 },
  { name: "BUDAPEST", lat: 47.5, lon: 19.0, country: "HUNGARY", region: "pact", pop: 1.7 },
  { name: "SOFIA", lat: 42.7, lon: 23.3, country: "BULGARIA", region: "bulgarian", pop: 1.2 },
  { name: "EAST BERLIN", lat: 52.5, lon: 13.4, country: "E.GERMANY", region: "pact", pop: 1.2 },
  { name: "TIRANA", lat: 41.3, lon: 19.8, country: "ALBANIA", region: "albanian", pop: 0.2 },
  { name: "BELGRADE", lat: 44.8, lon: 20.5, country: "YUGOSLAVIA", region: "pact", pop: 1.2 },
  // === MIDDLE EAST ===
  { name: "TEHRAN", lat: 35.7, lon: 51.4, country: "IRAN", region: "iranian", pop: 8.7 },
  { name: "ISFAHAN", lat: 32.7, lon: 51.7, country: "IRAN", region: "iranian", pop: 2.0 },
  { name: "BAGHDAD", lat: 33.3, lon: 44.4, country: "IRAQ", region: "iraq", pop: 7.1 },
  { name: "BASRA", lat: 30.5, lon: 47.8, country: "IRAQ", region: "iraq", pop: 1.3 },
  { name: "RIYADH", lat: 24.7, lon: 46.7, country: "SAUDI ARABIA", region: "saudi", pop: 5.2 },
  { name: "JEDDAH", lat: 21.5, lon: 39.2, country: "SAUDI ARABIA", region: "saudi", pop: 3.4 },
  { name: "TEL AVIV", lat: 32.1, lon: 34.8, country: "ISRAEL", region: "israel", pop: 0.5 },
  { name: "JERUSALEM", lat: 31.8, lon: 35.2, country: "ISRAEL", region: "israel", pop: 0.9 },
  { name: "BEIRUT", lat: 33.9, lon: 35.5, country: "LEBANON", region: "lebanon", pop: 0.4 },
  { name: "DAMASCUS", lat: 33.5, lon: 36.3, country: "SYRIA", region: "syrian", pop: 1.7 },
  { name: "ALEPPO", lat: 36.2, lon: 37.2, country: "SYRIA", region: "syrian", pop: 1.9 },
  { name: "CAIRO", lat: 30.0, lon: 31.2, country: "EGYPT", region: "egypt", pop: 9.5 },
  { name: "ALEXANDRIA", lat: 31.2, lon: 29.9, country: "EGYPT", region: "egypt", pop: 5.2 },
  { name: "AMMAN", lat: 31.9, lon: 35.9, country: "JORDAN", region: "israel", pop: 1.1 },
  { name: "KUWAIT CITY", lat: 29.4, lon: 47.9, country: "KUWAIT", region: "saudi", pop: 0.2 },
  { name: "MUSCAT", lat: 23.6, lon: 58.5, country: "OMAN", region: "saudi", pop: 0.8 },
  { name: "SANAA", lat: 15.4, lon: 44.2, country: "YEMEN", region: "saudi", pop: 1.9 },
  { name: "ABU DHABI", lat: 24.5, lon: 54.4, country: "UAE", region: "saudi", pop: 0.6 },
  { name: "DOHA", lat: 25.3, lon: 51.5, country: "QATAR", region: "saudi", pop: 0.3 },
  { name: "MANAMA", lat: 26.2, lon: 50.6, country: "BAHRAIN", region: "saudi", pop: 0.2 },
  // === AFRICA ===
  { name: "KHARTOUM", lat: 15.6, lon: 32.5, country: "SUDAN", region: "sudan", pop: 1.9 },
  { name: "KINSHASA", lat: -4.3, lon: 15.3, country: "ZAIRE", region: "zaire", pop: 3.0 },
  { name: "NDJAMENA", lat: 12.1, lon: 15.0, country: "CHAD", region: "chad", pop: 0.5 },
  { name: "ADDIS ABABA", lat: 9.0, lon: 38.7, country: "ETHIOPIA", region: "ethiopian", pop: 2.8 },
  { name: "NAIROBI", lat: -1.3, lon: 36.8, country: "KENYA", region: "kenya", pop: 3.1 },
  { name: "KAMPALA", lat: 0.3, lon: 32.6, country: "UGANDA", region: "uganda", pop: 1.7 },
  { name: "PRETORIA", lat: -25.7, lon: 28.2, country: "S.AFRICA", region: "s.african", pop: 0.7 },
  { name: "JOHANNESBURG", lat: -26.2, lon: 28.0, country: "S.AFRICA", region: "s.african", pop: 4.4 },
  { name: "CAPE TOWN", lat: -33.9, lon: 18.4, country: "S.AFRICA", region: "s.african", pop: 3.4 },
  { name: "LIBREVILLE", lat: 0.4, lon: 9.5, country: "GABON", region: "gabon", pop: 0.6 },
  { name: "RABAT", lat: 34.0, lon: -6.8, country: "MOROCCO", region: "moroccan", pop: 0.6 },
  { name: "CASABLANCA", lat: 33.6, lon: -7.6, country: "MOROCCO", region: "moroccan", pop: 3.4 },
  { name: "TUNIS", lat: 36.8, lon: 10.2, country: "TUNISIA", region: "tunisian", pop: 0.7 },
  { name: "ALGIERS", lat: 36.8, lon: 3.1, country: "ALGERIA", region: "algerian", pop: 2.4 },
  { name: "TRIPOLI", lat: 32.9, lon: 13.2, country: "LIBYA", region: "libyan", pop: 1.2 },
  { name: "LAGOS", lat: 6.5, lon: 3.4, country: "NIGERIA", region: "us", pop: 8.0 },
  { name: "ABUJA", lat: 9.1, lon: 7.5, country: "NIGERIA", region: "us", pop: 1.2 },
  { name: "ACCRA", lat: 5.6, lon: -0.2, country: "GHANA", region: "us", pop: 2.3 },
  { name: "DAKAR", lat: 14.7, lon: -17.5, country: "SENEGAL", region: "us", pop: 1.1 },
  { name: "ABIDJAN", lat: 5.3, lon: -4.0, country: "IVORY COAST", region: "us", pop: 2.9 },
  { name: "DAR ES SALAAM", lat: -6.8, lon: 39.3, country: "TANZANIA", region: "kenya", pop: 2.5 },
  { name: "LUANDA", lat: -8.8, lon: 13.2, country: "ANGOLA", region: "us", pop: 2.5 },
  { name: "MAPUTO", lat: -25.9, lon: 32.6, country: "MOZAMBIQUE", region: "s.african", pop: 1.1 },
  { name: "LUSAKA", lat: -15.4, lon: 28.3, country: "ZAMBIA", region: "us", pop: 1.3 },
  { name: "HARARE", lat: -17.8, lon: 31.0, country: "ZIMBABWE", region: "s.african", pop: 1.5 },
  { name: "MOGADISHU", lat: 2.0, lon: 45.3, country: "SOMALIA", region: "ethiopian", pop: 1.6 },
  { name: "ANTANANARIVO", lat: -18.9, lon: 47.5, country: "MADAGASCAR", region: "us", pop: 1.3 },
  { name: "BAMAKO", lat: 12.6, lon: -8.0, country: "MALI", region: "us", pop: 1.0 },
  { name: "CONAKRY", lat: 9.6, lon: -13.6, country: "GUINEA", region: "us", pop: 1.7 },
  { name: "YAOUNDE", lat: 3.9, lon: 11.5, country: "CAMEROON", region: "us", pop: 1.8 },
  { name: "BRAZZAVILLE", lat: -4.3, lon: 15.3, country: "CONGO", region: "zaire", pop: 1.2 },
  { name: "FREETOWN", lat: 8.5, lon: -13.2, country: "SIERRA LEONE", region: "us", pop: 0.8 },
  { name: "MONROVIA", lat: 6.3, lon: -10.8, country: "LIBERIA", region: "us", pop: 1.0 },
  { name: "NOUAKCHOTT", lat: 18.1, lon: -15.9, country: "MAURITANIA", region: "us", pop: 0.7 },
  { name: "NIAMEY", lat: 13.5, lon: 2.1, country: "NIGER", region: "chad", pop: 0.8 },
  { name: "OUAGADOUGOU", lat: 12.4, lon: -1.5, country: "BURKINA FASO", region: "us", pop: 1.1 },
  { name: "LOME", lat: 6.1, lon: 1.2, country: "TOGO", region: "us", pop: 0.8 },
  { name: "COTONOU", lat: 6.4, lon: 2.4, country: "BENIN", region: "us", pop: 0.7 },
  { name: "BANGUI", lat: 4.4, lon: 18.6, country: "CENTRAL AFRICAN REP", region: "chad", pop: 0.5 },
  { name: "BUJUMBURA", lat: -3.4, lon: 29.4, country: "BURUNDI", region: "uganda", pop: 0.3 },
  { name: "KIGALI", lat: -1.9, lon: 30.1, country: "RWANDA", region: "uganda", pop: 0.4 },
  { name: "WINDHOEK", lat: -22.6, lon: 17.1, country: "NAMIBIA", region: "s.african", pop: 0.3 },
  { name: "GABORONE", lat: -24.7, lon: 25.9, country: "BOTSWANA", region: "s.african", pop: 0.2 },
  { name: "ASMARA", lat: 15.3, lon: 38.9, country: "ERITREA", region: "ethiopian", pop: 0.5 },
  { name: "DJIBOUTI", lat: 11.6, lon: 43.1, country: "DJIBOUTI", region: "ethiopian", pop: 0.5 },
  // === SOUTH ASIA ===
  { name: "NEW DELHI", lat: 28.6, lon: 77.2, country: "INDIA", region: "india", pop: 10.9 },
  { name: "MUMBAI", lat: 19.1, lon: 72.9, country: "INDIA", region: "india", pop: 12.5 },
  { name: "CALCUTTA", lat: 22.6, lon: 88.4, country: "INDIA", region: "india", pop: 4.5 },
  { name: "CHENNAI", lat: 13.1, lon: 80.3, country: "INDIA", region: "india", pop: 4.7 },
  { name: "BANGALORE", lat: 13.0, lon: 77.6, country: "INDIA", region: "india", pop: 4.1 },
  { name: "HYDERABAD", lat: 17.4, lon: 78.5, country: "INDIA", region: "india", pop: 3.9 },
  { name: "ISLAMABAD", lat: 33.7, lon: 73.0, country: "PAKISTAN", region: "pakistan", pop: 1.0 },
  { name: "KARACHI", lat: 24.9, lon: 67.0, country: "PAKISTAN", region: "pakistan", pop: 14.9 },
  { name: "LAHORE", lat: 31.5, lon: 74.4, country: "PAKISTAN", region: "pakistan", pop: 6.3 },
  { name: "DHAKA", lat: 23.8, lon: 90.4, country: "BANGLADESH", region: "bangladesh", pop: 8.9 },
  { name: "COLOMBO", lat: 6.9, lon: 79.9, country: "SRI LANKA", region: "india", pop: 0.8 },
  { name: "KABUL", lat: 34.5, lon: 69.2, country: "AFGHANISTAN", region: "afghan", pop: 3.3 },
  { name: "KATHMANDU", lat: 27.7, lon: 85.3, country: "NEPAL", region: "india", pop: 1.0 },
  { name: "MALE", lat: 4.2, lon: 73.5, country: "MALDIVES", region: "india", pop: 0.1 },
  // === EAST ASIA ===
  { name: "BEIJING", lat: 39.9, lon: 116.4, country: "CHINA", region: "china", pop: 11.7 },
  { name: "SHANGHAI", lat: 31.2, lon: 121.5, country: "CHINA", region: "china", pop: 16.6 },
  { name: "GUANGZHOU", lat: 23.1, lon: 113.3, country: "CHINA", region: "china", pop: 8.5 },
  { name: "CHONGQING", lat: 29.6, lon: 106.5, country: "CHINA", region: "china", pop: 8.2 },
  { name: "TIANJIN", lat: 39.1, lon: 117.2, country: "CHINA", region: "china", pop: 7.5 },
  { name: "WUHAN", lat: 30.6, lon: 114.3, country: "CHINA", region: "china", pop: 6.4 },
  { name: "SHENYANG", lat: 41.8, lon: 123.4, country: "CHINA", region: "china", pop: 5.3 },
  { name: "CHENGDU", lat: 30.6, lon: 104.1, country: "CHINA", region: "china", pop: 7.4 },
  { name: "HONG KONG", lat: 22.3, lon: 114.2, country: "HONG KONG", region: "hongkong", pop: 5.0 },
  { name: "TAIPEI", lat: 25.0, lon: 121.5, country: "TAIWAN", region: "taiwan", pop: 2.6 },
  { name: "TOKYO", lat: 35.7, lon: 139.7, country: "JAPAN", region: "fareast", pop: 13.5 },
  { name: "OSAKA", lat: 34.7, lon: 135.5, country: "JAPAN", region: "fareast", pop: 2.7 },
  { name: "NAGOYA", lat: 35.2, lon: 136.9, country: "JAPAN", region: "fareast", pop: 2.3 },
  { name: "YOKOHAMA", lat: 35.4, lon: 139.6, country: "JAPAN", region: "fareast", pop: 3.7 },
  { name: "SEOUL", lat: 37.6, lon: 127.0, country: "S.KOREA", region: "fareast", pop: 9.8 },
  { name: "PYONGYANG", lat: 39.0, lon: 125.8, country: "N.KOREA", region: "fareast", pop: 2.6 },
  { name: "ULAANBAATAR", lat: 47.9, lon: 106.9, country: "MONGOLIA", region: "mongolian", pop: 1.0 },
  // === SOUTHEAST ASIA ===
  { name: "HANOI", lat: 21.0, lon: 105.9, country: "VIETNAM", region: "vietnamese", pop: 3.6 },
  { name: "HO CHI MINH CITY", lat: 10.8, lon: 106.6, country: "VIETNAM", region: "vietnamese", pop: 5.3 },
  { name: "BANGKOK", lat: 13.8, lon: 100.5, country: "THAILAND", region: "thai", pop: 5.7 },
  { name: "RANGOON", lat: 16.9, lon: 96.2, country: "BURMA", region: "burmese", pop: 4.5 },
  { name: "PHNOM PENH", lat: 11.6, lon: 104.9, country: "CAMBODIA", region: "cambodian", pop: 1.5 },
  { name: "VIENTIANE", lat: 17.9, lon: 102.6, country: "LAOS", region: "cambodian", pop: 0.2 },
  { name: "KUALA LUMPUR", lat: 3.1, lon: 101.7, country: "MALAYSIA", region: "malaysian", pop: 1.8 },
  { name: "SINGAPORE", lat: 1.3, lon: 103.8, country: "SINGAPORE", region: "seato", pop: 2.7 },
  { name: "JAKARTA", lat: -6.2, lon: 106.8, country: "INDONESIA", region: "seato", pop: 8.2 },
  { name: "SURABAYA", lat: -7.3, lon: 112.7, country: "INDONESIA", region: "seato", pop: 2.9 },
  { name: "MANILA", lat: 14.6, lon: 121.0, country: "PHILIPPINES", region: "seato", pop: 1.8 },
  { name: "BRUNEI", lat: 4.9, lon: 114.9, country: "BRUNEI", region: "malaysian", pop: 0.1 },
  // === OCEANIA ===
  { name: "CANBERRA", lat: -35.3, lon: 149.1, country: "AUSTRALIA", region: "australian", pop: 0.4 },
  { name: "SYDNEY", lat: -33.9, lon: 151.2, country: "AUSTRALIA", region: "australian", pop: 4.6 },
  { name: "MELBOURNE", lat: -37.8, lon: 145.0, country: "AUSTRALIA", region: "australian", pop: 4.0 },
  { name: "BRISBANE", lat: -27.5, lon: 153.0, country: "AUSTRALIA", region: "australian", pop: 1.9 },
  { name: "PERTH", lat: -31.9, lon: 115.9, country: "AUSTRALIA", region: "australian", pop: 1.6 },
  { name: "WELLINGTON", lat: -41.3, lon: 174.8, country: "NEW ZEALAND", region: "australian", pop: 0.2 },
  { name: "AUCKLAND", lat: -36.8, lon: 174.8, country: "NEW ZEALAND", region: "australian", pop: 1.5 },
  { name: "SUVA", lat: -18.1, lon: 178.4, country: "FIJI", region: "australian", pop: 0.1 },
  { name: "PORT MORESBY", lat: -9.4, lon: 147.2, country: "PAPUA NEW GUINEA", region: "australian", pop: 0.4 },
  // === MORE USSR ===
  { name: "KUYBYSHEV", lat: 53.2, lon: 50.1, country: "USSR", region: "ussr", pop: 1.3 },
  { name: "KRASNOYARSK", lat: 56.0, lon: 92.9, country: "USSR", region: "ussr", pop: 0.9 },
  { name: "OMSK", lat: 55.0, lon: 73.4, country: "USSR", region: "ussr", pop: 1.2 },
  { name: "CHELYABINSK", lat: 55.2, lon: 61.4, country: "USSR", region: "ussr", pop: 1.1 },
  { name: "KAZAN", lat: 55.8, lon: 49.1, country: "USSR", region: "ussr", pop: 1.1 },
  { name: "PERM", lat: 58.0, lon: 56.3, country: "USSR", region: "ussr", pop: 1.0 },
  { name: "UFA", lat: 54.7, lon: 55.9, country: "USSR", region: "ussr", pop: 1.1 },
  { name: "ROSTOV-ON-DON", lat: 47.2, lon: 39.7, country: "USSR", region: "ussr", pop: 1.0 },
  { name: "VORONEZH", lat: 51.7, lon: 39.2, country: "USSR", region: "ussr", pop: 0.9 },
  { name: "SARATOV", lat: 51.5, lon: 46.0, country: "USSR", region: "ussr", pop: 0.9 },
  { name: "KHABAROVSK", lat: 48.5, lon: 135.1, country: "USSR", region: "ussr", pop: 0.6 },
  { name: "IRKUTSK", lat: 52.3, lon: 104.3, country: "USSR", region: "ussr", pop: 0.6 },
  { name: "MAGADAN", lat: 59.6, lon: 150.8, country: "USSR", region: "arctic", pop: 0.2 },
  { name: "ARCHANGELSK", lat: 64.5, lon: 40.5, country: "USSR", region: "arctic", pop: 0.4 },
  { name: "PETROPAVLOVSK", lat: 53.0, lon: 158.6, country: "USSR", region: "ussr", pop: 0.2 },
  { name: "YEREVAN", lat: 40.2, lon: 44.5, country: "USSR", region: "ussr", pop: 1.2 },
  { name: "FRUNZE", lat: 42.9, lon: 74.6, country: "USSR", region: "ussr", pop: 0.6 },
  { name: "DUSHANBE", lat: 38.6, lon: 68.8, country: "USSR", region: "ussr", pop: 0.5 },
  { name: "ASHKHABAD", lat: 37.9, lon: 58.4, country: "USSR", region: "ussr", pop: 0.4 },
  { name: "VILNIUS", lat: 54.7, lon: 25.3, country: "USSR", region: "ussr", pop: 0.5 },
  { name: "TALLINN", lat: 59.4, lon: 24.7, country: "USSR", region: "ussr", pop: 0.4 },
  { name: "KISHINEV", lat: 47.0, lon: 28.8, country: "USSR", region: "ussr", pop: 0.6 },
  // === MORE CHINA ===
  { name: "XIAN", lat: 34.3, lon: 108.9, country: "CHINA", region: "china", pop: 3.2 },
  { name: "NANJING", lat: 32.1, lon: 118.8, country: "CHINA", region: "china", pop: 4.3 },
  { name: "HARBIN", lat: 45.8, lon: 126.6, country: "CHINA", region: "china", pop: 4.6 },
  { name: "CHANGCHUN", lat: 43.9, lon: 125.3, country: "CHINA", region: "china", pop: 3.5 },
  { name: "DALIAN", lat: 38.9, lon: 121.6, country: "CHINA", region: "china", pop: 2.7 },
  { name: "KUNMING", lat: 25.0, lon: 102.7, country: "CHINA", region: "china", pop: 2.7 },
  { name: "LANZHOU", lat: 36.1, lon: 103.8, country: "CHINA", region: "china", pop: 2.2 },
  { name: "URUMQI", lat: 43.8, lon: 87.6, country: "CHINA", region: "china", pop: 2.0 },
  { name: "LHASA", lat: 29.6, lon: 91.1, country: "CHINA", region: "china", pop: 0.3 },
  { name: "SHENZHEN", lat: 22.5, lon: 114.1, country: "CHINA", region: "china", pop: 3.5 },
  // === MORE US ===
  { name: "PITTSBURGH", lat: 40.4, lon: -80.0, country: "US", region: "us", pop: 0.3 },
  { name: "OMAHA", lat: 41.3, lon: -95.9, country: "US", region: "us", pop: 0.5 },
  { name: "NORFOLK", lat: 36.8, lon: -76.3, country: "US", region: "us", pop: 0.2 },
  { name: "COLORADO SPRINGS", lat: 38.8, lon: -104.8, country: "US", region: "us", pop: 0.5 },
  { name: "SAN JOSE CA", lat: 37.3, lon: -121.9, country: "US", region: "us", pop: 1.0 },
  { name: "TAMPA", lat: 28.0, lon: -82.5, country: "US", region: "us", pop: 0.4 },
  { name: "NEW ORLEANS", lat: 30.0, lon: -90.1, country: "US", region: "us", pop: 0.4 },
  { name: "KANSAS CITY", lat: 39.1, lon: -94.6, country: "US", region: "us", pop: 0.5 },
  { name: "INDIANAPOLIS", lat: 39.8, lon: -86.2, country: "US", region: "us", pop: 0.9 },
  { name: "PORTLAND", lat: 45.5, lon: -122.7, country: "US", region: "us", pop: 0.7 },
  { name: "LAS VEGAS", lat: 36.2, lon: -115.1, country: "US", region: "us", pop: 0.6 },
  { name: "SALT LAKE CITY", lat: 40.8, lon: -111.9, country: "US", region: "us", pop: 0.2 },
  { name: "CHARLESTON", lat: 32.8, lon: -79.9, country: "US", region: "us", pop: 0.1 },
  { name: "NASHVILLE", lat: 36.2, lon: -86.8, country: "US", region: "us", pop: 0.2 },
  { name: "KNOXVILLE", lat: 35.9, lon: -83.9, country: "US", region: "us", pop: 0.1 },
  { name: "MEMPHIS", lat: 35.1, lon: -90.0, country: "US", region: "us", pop: 0.4 },
  { name: "CHATTANOOGA", lat: 35.0, lon: -85.3, country: "US", region: "us", pop: 0.1 },
  { name: "LOUISVILLE", lat: 38.3, lon: -85.8, country: "US", region: "us", pop: 0.4 },
  { name: "BOWLING GREEN", lat: 37.0, lon: -86.4, country: "US", region: "us", pop: 0.1 },
  { name: "BIRMINGHAM AL", lat: 33.5, lon: -86.8, country: "US", region: "us", pop: 0.3 },
  { name: "CHARLOTTESVILLE", lat: 38.0, lon: -78.5, country: "US", region: "us", pop: 0.05 },
  { name: "ERIE", lat: 42.1, lon: -80.1, country: "US", region: "us", pop: 0.1 },
  { name: "BUFFALO", lat: 42.9, lon: -78.9, country: "US", region: "us", pop: 0.6 },
  { name: "BLOOMINGTON", lat: 39.2, lon: -86.5, country: "US", region: "us", pop: 0.05 },
  // === MORE NATO / EUROPE ===
  { name: "FRANKFURT", lat: 50.1, lon: 8.7, country: "W.GERMANY", region: "nato", pop: 0.7 },
  { name: "COLOGNE", lat: 50.9, lon: 6.9, country: "W.GERMANY", region: "nato", pop: 1.0 },
  { name: "BONN", lat: 50.7, lon: 7.1, country: "W.GERMANY", region: "nato", pop: 0.3 },
  { name: "TOULOUSE", lat: 43.6, lon: 1.4, country: "FRANCE", region: "french", pop: 0.4 },
  { name: "NICE", lat: 43.7, lon: 7.3, country: "FRANCE", region: "french", pop: 0.3 },
  { name: "EDINBURGH", lat: 55.9, lon: -3.2, country: "UK", region: "english", pop: 0.5 },
  { name: "MANCHESTER", lat: 53.5, lon: -2.2, country: "UK", region: "english", pop: 0.5 },
  { name: "LIVERPOOL", lat: 53.4, lon: -3.0, country: "UK", region: "english", pop: 0.5 },
  { name: "PALERMO", lat: 38.1, lon: 13.4, country: "ITALY", region: "italian", pop: 0.7 },
  { name: "TURIN", lat: 45.1, lon: 7.7, country: "ITALY", region: "italian", pop: 0.9 },
  { name: "VALENCIA", lat: 39.5, lon: -0.4, country: "SPAIN", region: "nato", pop: 0.8 },
  { name: "SEVILLE", lat: 37.4, lon: -6.0, country: "SPAIN", region: "nato", pop: 0.7 },
  { name: "GOTHENBURG", lat: 57.7, lon: 12.0, country: "SWEDEN", region: "nato", pop: 0.6 },
  { name: "ROTTERDAM", lat: 51.9, lon: 4.5, country: "NETHERLANDS", region: "nato", pop: 0.6 },
  { name: "GDANSK", lat: 54.4, lon: 18.6, country: "POLAND", region: "pact", pop: 0.5 },
  { name: "WROCLAW", lat: 51.1, lon: 17.0, country: "POLAND", region: "pact", pop: 0.6 },
  { name: "BRATISLAVA", lat: 48.1, lon: 17.1, country: "CZECHOSLOVAKIA", region: "czech", pop: 0.4 },
  { name: "ZAGREB", lat: 45.8, lon: 16.0, country: "YUGOSLAVIA", region: "pact", pop: 0.7 },
  { name: "THESSALONIKI", lat: 40.6, lon: 22.9, country: "GREECE", region: "nato", pop: 1.1 },
  { name: "IZMIR", lat: 38.4, lon: 27.1, country: "TURKEY", region: "turkish", pop: 2.9 },
  { name: "CONSTANTA", lat: 44.2, lon: 28.6, country: "ROMANIA", region: "romanian", pop: 0.3 },
  { name: "VARNA", lat: 43.2, lon: 27.9, country: "BULGARIA", region: "bulgarian", pop: 0.3 },
  { name: "DEBRECEN", lat: 47.5, lon: 21.6, country: "HUNGARY", region: "pact", pop: 0.2 },
  { name: "DRESDEN", lat: 51.1, lon: 13.7, country: "E.GERMANY", region: "pact", pop: 0.5 },
  { name: "LEIPZIG", lat: 51.3, lon: 12.4, country: "E.GERMANY", region: "pact", pop: 0.5 },
  // === MORE MIDDLE EAST ===
  { name: "TABRIZ", lat: 38.1, lon: 46.3, country: "IRAN", region: "iranian", pop: 1.6 },
  { name: "MOSUL", lat: 36.3, lon: 43.1, country: "IRAQ", region: "iraq", pop: 0.7 },
  { name: "MECCA", lat: 21.4, lon: 39.8, country: "SAUDI ARABIA", region: "saudi", pop: 1.5 },
  { name: "MEDINA", lat: 24.5, lon: 39.6, country: "SAUDI ARABIA", region: "saudi", pop: 1.2 },
  { name: "ADEN", lat: 12.8, lon: 45.0, country: "YEMEN", region: "saudi", pop: 0.6 },
  // === MORE INDIA ===
  { name: "AHMEDABAD", lat: 23.0, lon: 72.6, country: "INDIA", region: "india", pop: 3.5 },
  { name: "PUNE", lat: 18.5, lon: 73.9, country: "INDIA", region: "india", pop: 3.1 },
  { name: "JAIPUR", lat: 26.9, lon: 75.8, country: "INDIA", region: "india", pop: 3.0 },
  { name: "LUCKNOW", lat: 26.8, lon: 80.9, country: "INDIA", region: "india", pop: 2.8 },
  { name: "KANPUR", lat: 26.4, lon: 80.4, country: "INDIA", region: "india", pop: 2.8 },
  // === MORE EAST ASIA ===
  { name: "SAPPORO", lat: 43.1, lon: 141.3, country: "JAPAN", region: "fareast", pop: 1.9 },
  { name: "FUKUOKA", lat: 33.6, lon: 130.4, country: "JAPAN", region: "fareast", pop: 1.6 },
  { name: "KOBE", lat: 34.7, lon: 135.2, country: "JAPAN", region: "fareast", pop: 1.5 },
  { name: "BUSAN", lat: 35.2, lon: 129.1, country: "S.KOREA", region: "fareast", pop: 3.5 },
  { name: "INCHEON", lat: 37.5, lon: 126.7, country: "S.KOREA", region: "fareast", pop: 2.9 },
  { name: "KAOHSIUNG", lat: 22.6, lon: 120.3, country: "TAIWAN", region: "taiwan", pop: 1.5 },
  { name: "MACAU", lat: 22.2, lon: 113.5, country: "MACAU", region: "hongkong", pop: 0.5 },
  // === MORE SOUTHEAST ASIA ===
  { name: "CEBU", lat: 10.3, lon: 123.9, country: "PHILIPPINES", region: "seato", pop: 0.9 },
  { name: "BANDUNG", lat: -6.9, lon: 107.6, country: "INDONESIA", region: "seato", pop: 2.4 },
  { name: "MEDAN", lat: 3.6, lon: 98.7, country: "INDONESIA", region: "seato", pop: 2.1 },
  { name: "CHIANG MAI", lat: 18.8, lon: 99.0, country: "THAILAND", region: "thai", pop: 0.2 },
  { name: "DA NANG", lat: 16.1, lon: 108.2, country: "VIETNAM", region: "vietnamese", pop: 0.5 },
  { name: "MANDALAY", lat: 21.9, lon: 96.1, country: "BURMA", region: "burmese", pop: 1.2 },
  // === MORE AFRICA ===
  { name: "DURBAN", lat: -29.9, lon: 31.0, country: "S.AFRICA", region: "s.african", pop: 3.1 },
  { name: "MOMBASA", lat: -4.1, lon: 39.7, country: "KENYA", region: "kenya", pop: 0.8 },
  { name: "DOUALA", lat: 4.0, lon: 9.7, country: "CAMEROON", region: "us", pop: 1.3 },
  { name: "BENGHAZI", lat: 32.1, lon: 20.1, country: "LIBYA", region: "libyan", pop: 0.7 },
  { name: "ORAN", lat: 35.7, lon: -0.6, country: "ALGERIA", region: "algerian", pop: 0.8 },
  { name: "IBADAN", lat: 7.4, lon: 3.9, country: "NIGERIA", region: "us", pop: 3.6 },
  { name: "PORT HARCOURT", lat: 4.8, lon: 7.0, country: "NIGERIA", region: "us", pop: 1.1 },
  { name: "LILONGWE", lat: -13.9, lon: 33.8, country: "MALAWI", region: "kenya", pop: 0.4 },
  { name: "BLANTYRE", lat: -15.8, lon: 35.0, country: "MALAWI", region: "kenya", pop: 0.5 },
  { name: "LAMU", lat: -2.3, lon: 40.9, country: "KENYA", region: "kenya", pop: 0.03 },
  // === MORE SOUTH AMERICA ===
  { name: "RECIFE", lat: -8.1, lon: -34.9, country: "BRAZIL", region: "brazilian", pop: 1.5 },
  { name: "SALVADOR", lat: -12.9, lon: -38.5, country: "BRAZIL", region: "brazilian", pop: 2.7 },
  { name: "BELO HORIZONTE", lat: -19.9, lon: -43.9, country: "BRAZIL", region: "brazilian", pop: 2.5 },
  { name: "PORTO ALEGRE", lat: -30.0, lon: -51.2, country: "BRAZIL", region: "brazilian", pop: 1.4 },
  { name: "CORDOBA", lat: -31.4, lon: -64.2, country: "ARGENTINA", region: "argentina", pop: 1.3 },
  { name: "ROSARIO", lat: -32.9, lon: -60.7, country: "ARGENTINA", region: "argentina", pop: 1.2 },
  { name: "MEDELLIN", lat: 6.2, lon: -75.6, country: "COLOMBIA", region: "us", pop: 2.5 },
  { name: "CALI", lat: 3.4, lon: -76.5, country: "COLOMBIA", region: "us", pop: 2.2 },
  { name: "GUAYAQUIL", lat: -2.2, lon: -79.9, country: "ECUADOR", region: "us", pop: 2.3 },
  { name: "MARACAIBO", lat: 10.7, lon: -71.6, country: "VENEZUELA", region: "venezuela", pop: 1.5 },
  { name: "VALPARAISO", lat: -33.0, lon: -71.6, country: "CHILE", region: "chile", pop: 0.3 },
  // === PACIFIC ISLANDS ===
  { name: "GUAM", lat: 13.4, lon: 144.8, country: "US", region: "us", pop: 0.2 },
  // === ARCTIC / OTHER ===
  { name: "NUUK", lat: 64.2, lon: -51.7, country: "GREENLAND", region: "greenland", pop: 0.02 },
  // === ADDITIONAL CAPITALS & CITIES ===
  { name: "BELFAST", lat: 54.6, lon: -5.9, country: "UK", region: "english", pop: 0.3 },
  { name: "CARDIFF", lat: 51.5, lon: -3.2, country: "UK", region: "english", pop: 0.4 },
  { name: "STRASBOURG", lat: 48.6, lon: 7.8, country: "FRANCE", region: "french", pop: 0.3 },
  { name: "GENOA", lat: 44.4, lon: 8.9, country: "ITALY", region: "italian", pop: 0.6 },
  { name: "FLORENCE", lat: 43.8, lon: 11.3, country: "ITALY", region: "italian", pop: 0.4 },
  { name: "MALAGA", lat: 36.7, lon: -4.4, country: "SPAIN", region: "nato", pop: 0.6 },
  { name: "BILBAO", lat: 43.3, lon: -2.9, country: "SPAIN", region: "nato", pop: 0.4 },
  { name: "PORTO", lat: 41.2, lon: -8.6, country: "PORTUGAL", region: "portugal", pop: 0.2 },
  { name: "ANTWERP", lat: 51.2, lon: 4.4, country: "BELGIUM", region: "nato", pop: 0.5 },
  { name: "THE HAGUE", lat: 52.1, lon: 4.3, country: "NETHERLANDS", region: "nato", pop: 0.5 },
  { name: "BERGEN", lat: 60.4, lon: 5.3, country: "NORWAY", region: "nato", pop: 0.3 },
  { name: "TAMPERE", lat: 61.5, lon: 23.8, country: "FINLAND", region: "nato", pop: 0.2 },
  { name: "POZNAN", lat: 52.4, lon: 16.9, country: "POLAND", region: "pact", pop: 0.5 },
  { name: "LODZ", lat: 51.8, lon: 19.5, country: "POLAND", region: "pact", pop: 0.7 },
  { name: "TIMISOARA", lat: 45.8, lon: 21.2, country: "ROMANIA", region: "romanian", pop: 0.3 },
  { name: "PLOVDIV", lat: 42.1, lon: 24.7, country: "BULGARIA", region: "bulgarian", pop: 0.3 },
  { name: "SPLIT", lat: 43.5, lon: 16.4, country: "YUGOSLAVIA", region: "pact", pop: 0.2 },
  { name: "SARAJEVO", lat: 43.9, lon: 18.4, country: "YUGOSLAVIA", region: "pact", pop: 0.4 },
  { name: "SKOPJE", lat: 42.0, lon: 21.4, country: "YUGOSLAVIA", region: "pact", pop: 0.4 },
  { name: "ADANA", lat: 37.0, lon: 35.3, country: "TURKEY", region: "turkish", pop: 1.8 },
  { name: "ANTALYA", lat: 36.9, lon: 30.7, country: "TURKEY", region: "turkish", pop: 1.2 },
  // === MORE ASIAN CITIES ===
  { name: "CHANGSHA", lat: 28.2, lon: 113.0, country: "CHINA", region: "china", pop: 3.6 },
  { name: "HANGZHOU", lat: 30.3, lon: 120.2, country: "CHINA", region: "china", pop: 4.1 },
  { name: "ZHENGZHOU", lat: 34.7, lon: 113.6, country: "CHINA", region: "china", pop: 4.3 },
  { name: "JINAN", lat: 36.7, lon: 117.0, country: "CHINA", region: "china", pop: 3.5 },
  { name: "QINGDAO", lat: 36.1, lon: 120.4, country: "CHINA", region: "china", pop: 3.1 },
  { name: "XIAMEN", lat: 24.5, lon: 118.1, country: "CHINA", region: "china", pop: 2.1 },
  { name: "CHITTAGONG", lat: 22.4, lon: 91.8, country: "BANGLADESH", region: "bangladesh", pop: 2.6 },
  { name: "RAWALPINDI", lat: 33.6, lon: 73.0, country: "PAKISTAN", region: "pakistan", pop: 2.0 },
  { name: "FAISALABAD", lat: 31.4, lon: 73.1, country: "PAKISTAN", region: "pakistan", pop: 2.0 },
  { name: "NAGPUR", lat: 21.1, lon: 79.1, country: "INDIA", region: "india", pop: 2.4 },
  { name: "VARANASI", lat: 25.3, lon: 83.0, country: "INDIA", region: "india", pop: 1.2 },
  { name: "PATNA", lat: 25.6, lon: 85.1, country: "INDIA", region: "india", pop: 1.7 },
  { name: "HIROSHIMA", lat: 34.4, lon: 132.5, country: "JAPAN", region: "fareast", pop: 1.2 },
  { name: "SENDAI", lat: 38.3, lon: 140.9, country: "JAPAN", region: "fareast", pop: 1.1 },
  { name: "DAVAO", lat: 7.1, lon: 125.6, country: "PHILIPPINES", region: "seato", pop: 1.6 },
  { name: "SEMARANG", lat: -7.0, lon: 110.4, country: "INDONESIA", region: "seato", pop: 1.6 },
  { name: "MAKASSAR", lat: -5.1, lon: 119.4, country: "INDONESIA", region: "seato", pop: 1.3 },
  // === MORE AFRICA ===
  { name: "KUMASI", lat: 6.7, lon: -1.6, country: "GHANA", region: "us", pop: 1.5 },
  { name: "KANO", lat: 12.0, lon: 8.5, country: "NIGERIA", region: "us", pop: 3.6 },
  { name: "LUBUMBASHI", lat: -11.7, lon: 27.5, country: "ZAIRE", region: "zaire", pop: 1.0 },
  { name: "TANTA", lat: 30.8, lon: 31.0, country: "EGYPT", region: "egypt", pop: 0.5 },
  { name: "FEZ", lat: 34.0, lon: -5.0, country: "MOROCCO", region: "moroccan", pop: 1.1 },
  { name: "MARRAKECH", lat: 31.6, lon: -8.0, country: "MOROCCO", region: "moroccan", pop: 0.9 },
  { name: "PORT ELIZABETH", lat: -33.9, lon: 25.6, country: "S.AFRICA", region: "s.african", pop: 0.8 },
  // === MORE AMERICAS ===
  { name: "CALGARY", lat: 51.0, lon: -114.1, country: "CANADA", region: "canada", pop: 1.0 },
  { name: "EDMONTON", lat: 53.5, lon: -113.5, country: "CANADA", region: "canada", pop: 0.9 },
  { name: "WINNIPEG", lat: 49.9, lon: -97.1, country: "CANADA", region: "canada", pop: 0.7 },
  { name: "QUEBEC CITY", lat: 46.8, lon: -71.2, country: "CANADA", region: "canada", pop: 0.5 },
  { name: "HALIFAX", lat: 44.6, lon: -63.6, country: "CANADA", region: "canada", pop: 0.4 },
  { name: "PUEBLA", lat: 19.0, lon: -98.2, country: "MEXICO", region: "mexico", pop: 1.5 },
  { name: "TIJUANA", lat: 32.5, lon: -117.0, country: "MEXICO", region: "mexico", pop: 1.8 },
  { name: "MANAUS", lat: -3.1, lon: -60.0, country: "BRAZIL", region: "brazilian", pop: 1.8 },
  { name: "FORTALEZA", lat: -3.7, lon: -38.5, country: "BRAZIL", region: "brazilian", pop: 2.5 },
  { name: "CURITIBA", lat: -25.4, lon: -49.3, country: "BRAZIL", region: "brazilian", pop: 1.9 },
  { name: "BARRANQUILLA", lat: 10.96, lon: -74.8, country: "COLOMBIA", region: "us", pop: 1.2 },
  { name: "AREQUIPA", lat: -16.4, lon: -71.5, country: "PERU", region: "us", pop: 0.8 },
  { name: "TUCUMAN", lat: -26.8, lon: -65.2, country: "ARGENTINA", region: "argentina", pop: 0.5 },
  { name: "CONCEPCION", lat: -36.8, lon: -73.0, country: "CHILE", region: "chile", pop: 0.2 },
  { name: "DARWIN", lat: -12.5, lon: 130.8, country: "AUSTRALIA", region: "australian", pop: 0.1 },
  { name: "ADELAIDE", lat: -34.9, lon: 138.6, country: "AUSTRALIA", region: "australian", pop: 1.3 },
];

// === ERA-SPECIFIC DATA ===
// Military bases, SSBNs, and embedded scenarios are keyed by era.
// switchEra() swaps the active data sets.

const MILITARY_BASES_1957 = [
  // === US — STRATEGIC COMMAND ===
  { name: "SAC HQ (OFFUTT AFB)", lat: 41.12, lon: -95.91, country: "US", region: "us", type: "base", pop: 0 },
  { name: "PENTAGON", lat: 38.87, lon: -77.06, country: "US", region: "us", type: "base", pop: 0 },
  { name: "NORAD (ENT AFB)", lat: 38.82, lon: -104.71, country: "US", region: "us", type: "base", pop: 0 },
  // === US — SAC BOMBER BASES (B-47 / B-52 wings) ===
  { name: "BARKSDALE AFB", lat: 32.50, lon: -93.66, country: "US", region: "us", type: "base", pop: 0 },
  { name: "LORING AFB", lat: 46.95, lon: -67.89, country: "US", region: "us", type: "base", pop: 0 },
  { name: "CASTLE AFB", lat: 37.38, lon: -120.57, country: "US", region: "us", type: "base", pop: 0 },
  { name: "MARCH AFB", lat: 33.88, lon: -117.26, country: "US", region: "us", type: "base", pop: 0 },
  { name: "PEASE AFB", lat: 43.08, lon: -70.82, country: "US", region: "us", type: "base", pop: 0 },
  { name: "FAIRCHILD AFB", lat: 47.62, lon: -117.66, country: "US", region: "us", type: "base", pop: 0 },
  { name: "TRAVIS AFB", lat: 38.26, lon: -121.93, country: "US", region: "us", type: "base", pop: 0 },
  { name: "HOMESTEAD AFB", lat: 25.49, lon: -80.38, country: "US", region: "us", type: "base", pop: 0 },
  { name: "GRIFFISS AFB", lat: 43.23, lon: -75.41, country: "US", region: "us", type: "base", pop: 0 },
  { name: "ELLSWORTH AFB", lat: 44.15, lon: -103.10, country: "US", region: "us", type: "base", pop: 0 },
  { name: "CARSWELL AFB", lat: 32.77, lon: -97.44, country: "US", region: "us", type: "base", pop: 0 },
  { name: "LIMESTONE AFB", lat: 46.95, lon: -67.89, country: "US", region: "us", type: "base", pop: 0 },
  { name: "WALKER AFB", lat: 33.30, lon: -104.53, country: "US", region: "us", type: "base", pop: 0 },
  // === US — FORWARD SAC BASES (refueling/staging) ===
  { name: "ELMENDORF AFB", lat: 61.25, lon: -149.81, country: "US", region: "alaska", type: "base", pop: 0 },
  { name: "EIELSON AFB", lat: 64.66, lon: -147.10, country: "US", region: "alaska", type: "base", pop: 0 },
  { name: "HICKAM AFB", lat: 21.32, lon: -157.94, country: "US", region: "hawaii", type: "base", pop: 0 },
  { name: "NORFOLK NB", lat: 36.95, lon: -76.33, country: "US", region: "us", type: "base", pop: 0 },
  // === US — EARLY WARNING ===
  { name: "THULE AB", lat: 76.53, lon: -68.70, country: "DENMARK", region: "nato", type: "base", pop: 0 },
  { name: "CAPE CANAVERAL", lat: 28.49, lon: -80.58, country: "US", region: "us", type: "base", pop: 0 },
  // === NATO — UK (V-BOMBER FORCE / USAF) ===
  { name: "RAF SCAMPTON", lat: 53.31, lon: -0.55, country: "UK", region: "uk", type: "base", pop: 0 },
  { name: "RAF WADDINGTON", lat: 53.17, lon: -0.52, country: "UK", region: "uk", type: "base", pop: 0 },
  { name: "RAF MARHAM", lat: 52.65, lon: 0.55, country: "UK", region: "uk", type: "base", pop: 0 },
  { name: "RAF HONINGTON", lat: 52.34, lon: 0.77, country: "UK", region: "uk", type: "base", pop: 0 },
  { name: "RAF LAKENHEATH", lat: 52.41, lon: 0.56, country: "UK", region: "uk", type: "base", pop: 0 },
  { name: "RAF MILDENHALL", lat: 52.36, lon: 0.49, country: "UK", region: "uk", type: "base", pop: 0 },
  { name: "RAF UPPER HEYFORD", lat: 51.93, lon: -1.25, country: "UK", region: "uk", type: "base", pop: 0 },
  { name: "RAF BRIZE NORTON", lat: 51.75, lon: -1.58, country: "UK", region: "uk", type: "base", pop: 0 },
  // === NATO — WEST GERMANY ===
  { name: "RAMMSTEIN AB", lat: 49.44, lon: 7.60, country: "W.GERMANY", region: "nato", type: "base", pop: 0 },
  { name: "BITBURG AB", lat: 49.95, lon: 6.57, country: "W.GERMANY", region: "nato", type: "base", pop: 0 },
  { name: "SPANGDAHLEM AB", lat: 49.97, lon: 6.69, country: "W.GERMANY", region: "nato", type: "base", pop: 0 },
  { name: "HAHN AB", lat: 49.95, lon: 7.26, country: "W.GERMANY", region: "nato", type: "base", pop: 0 },
  { name: "FULDA GAP", lat: 50.55, lon: 9.68, country: "W.GERMANY", region: "nato", type: "base", pop: 0 },
  // === NATO — OTHER EUROPE ===
  { name: "KEFLAVIK NAS", lat: 63.97, lon: -22.61, country: "ICELAND", region: "nato", type: "base", pop: 0 },
  { name: "AVIANO AB", lat: 46.03, lon: 12.60, country: "ITALY", region: "italian", type: "base", pop: 0 },
  { name: "INCIRLIK AB", lat: 37.00, lon: 35.43, country: "TURKEY", region: "turkish", type: "base", pop: 0 },
  { name: "WHEELUS AB", lat: 32.90, lon: 13.28, country: "LIBYA", region: "nato", type: "base", pop: 0 },
  { name: "NOUASSEUR AB", lat: 33.37, lon: -7.59, country: "MOROCCO", region: "nato", type: "base", pop: 0 },
  { name: "SIDI SLIMANE AB", lat: 34.23, lon: -6.05, country: "MOROCCO", region: "nato", type: "base", pop: 0 },
  { name: "BEN GUERIR AB", lat: 32.10, lon: -7.95, country: "MOROCCO", region: "nato", type: "base", pop: 0 },
  // === NATO — FAR EAST ===
  { name: "YOKOTA AB", lat: 35.75, lon: 139.35, country: "JAPAN", region: "fareast", type: "base", pop: 0 },
  { name: "KADENA AB", lat: 26.35, lon: 127.77, country: "JAPAN", region: "fareast", type: "base", pop: 0 },
  { name: "OSAN AB", lat: 37.09, lon: 127.03, country: "S.KOREA", region: "fareast", type: "base", pop: 0 },
  // === USSR — STRATEGIC COMMAND ===
  { name: "MOSCOW PVO HQ", lat: 55.75, lon: 37.62, country: "USSR", region: "ussr", type: "base", pop: 0 },
  // === USSR — LONG RANGE AVIATION (DA) BOMBER BASES ===
  { name: "ENGELS AB", lat: 51.48, lon: 46.20, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "UKRAINKA AB", lat: 51.17, lon: 128.40, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "MOZDOK AB", lat: 43.79, lon: 44.59, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "UZIN AB", lat: 49.80, lon: 30.45, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "POLTAVA AB", lat: 49.60, lon: 34.54, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "SOLTSY AB", lat: 58.14, lon: 30.32, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "TARTU AB", lat: 58.38, lon: 26.72, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "SHAYKOVKA AB", lat: 54.18, lon: 34.04, country: "USSR", region: "ussr", type: "base", pop: 0 },
  // === USSR — NAVAL BASES ===
  { name: "POLYARNY (NORTH FLEET)", lat: 69.20, lon: 33.47, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "SEVERODVINSK", lat: 64.57, lon: 39.85, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "VLADIVOSTOK NB", lat: 43.12, lon: 131.90, country: "USSR", region: "ussr", type: "base", pop: 0 },
  // === USSR — TEST / EARLY WARNING ===
  { name: "SEMIPALATINSK (TEST SITE)", lat: 50.07, lon: 78.43, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "BAIKONUR COSMODROME", lat: 45.97, lon: 63.31, country: "USSR", region: "ussr", type: "base", pop: 0 },
  // === USSR — FORWARD DEPLOYED (WARSAW PACT) ===
  { name: "WUNSDORF (GSFG HQ)", lat: 52.17, lon: 13.47, country: "E.GERMANY", region: "pact", type: "base", pop: 0 },
  { name: "BRAND AB", lat: 52.10, lon: 13.77, country: "E.GERMANY", region: "pact", type: "base", pop: 0 },
  { name: "LEGNICA (NORTHERN GROUP)", lat: 51.21, lon: 16.16, country: "POLAND", region: "pact", type: "base", pop: 0 },
  { name: "MILOVICE", lat: 50.23, lon: 14.89, country: "CZECHOSLOVAKIA", region: "pact", type: "base", pop: 0 },
];

const MILITARY_BASES_1983 = [
  // === US — STRATEGIC COMMAND ===
  { name: "NORAD", lat: 38.74, lon: -104.84, country: "US", region: "us", type: "base", pop: 0 },
  { name: "SAC HQ (OFFUTT AFB)", lat: 41.12, lon: -95.91, country: "US", region: "us", type: "base", pop: 0 },
  { name: "PENTAGON", lat: 38.87, lon: -77.06, country: "US", region: "us", type: "base", pop: 0 },
  // === US — ICBM FIELDS ===
  { name: "MALMSTROM AFB", lat: 47.51, lon: -111.18, country: "US", region: "us", type: "base", pop: 0 },
  { name: "MINOT AFB", lat: 48.42, lon: -101.36, country: "US", region: "us", type: "base", pop: 0 },
  { name: "F.E. WARREN AFB", lat: 41.15, lon: -104.87, country: "US", region: "us", type: "base", pop: 0 },
  { name: "WHITEMAN AFB", lat: 38.73, lon: -93.55, country: "US", region: "us", type: "base", pop: 0 },
  { name: "GRAND FORKS AFB", lat: 47.97, lon: -97.40, country: "US", region: "us", type: "base", pop: 0 },
  // === US — STRATEGIC BOMBER BASES ===
  { name: "BARKSDALE AFB", lat: 32.50, lon: -93.66, country: "US", region: "us", type: "base", pop: 0 },
  { name: "ELLSWORTH AFB", lat: 44.15, lon: -103.10, country: "US", region: "us", type: "base", pop: 0 },
  { name: "DYESS AFB", lat: 32.42, lon: -99.85, country: "US", region: "us", type: "base", pop: 0 },
  { name: "GRIFFISS AFB", lat: 43.23, lon: -75.41, country: "US", region: "us", type: "base", pop: 0 },
  { name: "LORING AFB", lat: 46.95, lon: -67.89, country: "US", region: "us", type: "base", pop: 0 },
  { name: "CASTLE AFB", lat: 37.38, lon: -120.57, country: "US", region: "us", type: "base", pop: 0 },
  // === US — SUBMARINE BASES ===
  { name: "KINGS BAY NSB", lat: 30.80, lon: -81.56, country: "US", region: "us", type: "base", pop: 0 },
  { name: "BANGOR NSB", lat: 47.72, lon: -122.71, country: "US", region: "us", type: "base", pop: 0 },
  { name: "HOLY LOCH (US)", lat: 55.98, lon: -4.93, country: "UK", region: "uk", type: "base", pop: 0 },
  // === US — PACIFIC / ATLANTIC ===
  { name: "ELMENDORF AFB", lat: 61.25, lon: -149.81, country: "US", region: "alaska", type: "base", pop: 0 },
  { name: "EIELSON AFB", lat: 64.66, lon: -147.10, country: "US", region: "alaska", type: "base", pop: 0 },
  { name: "HICKAM AFB", lat: 21.32, lon: -157.94, country: "US", region: "hawaii", type: "base", pop: 0 },
  { name: "PEARL HARBOR", lat: 21.35, lon: -157.97, country: "US", region: "hawaii", type: "base", pop: 0 },
  { name: "NORFOLK NB", lat: 36.95, lon: -76.33, country: "US", region: "us", type: "base", pop: 0 },
  { name: "CAMP PENDLETON", lat: 33.30, lon: -117.35, country: "US", region: "us", type: "base", pop: 0 },
  // === US — EARLY WARNING / COMMS ===
  { name: "THULE AB", lat: 76.53, lon: -68.70, country: "DENMARK", region: "nato", type: "base", pop: 0 },
  { name: "CLEAR AFS", lat: 64.30, lon: -149.19, country: "US", region: "alaska", type: "base", pop: 0 },
  { name: "CAPE CANAVERAL", lat: 28.49, lon: -80.58, country: "US", region: "us", type: "base", pop: 0 },
  { name: "VANDENBERG AFB", lat: 34.73, lon: -120.57, country: "US", region: "us", type: "base", pop: 0 },
  // === NATO — UK ===
  { name: "RAF LAKENHEATH", lat: 52.41, lon: 0.56, country: "UK", region: "uk", type: "base", pop: 0 },
  { name: "RAF MILDENHALL", lat: 52.36, lon: 0.49, country: "UK", region: "uk", type: "base", pop: 0 },
  { name: "RAF BENTWATERS", lat: 52.13, lon: 1.44, country: "UK", region: "uk", type: "base", pop: 0 },
  { name: "RAF UPPER HEYFORD", lat: 51.93, lon: -1.25, country: "UK", region: "uk", type: "base", pop: 0 },
  { name: "RAF GREENHAM COMMON", lat: 51.38, lon: -1.28, country: "UK", region: "uk", type: "base", pop: 0 },
  { name: "RAF FYLINGDALES", lat: 54.36, lon: -0.67, country: "UK", region: "uk", type: "base", pop: 0 },
  { name: "FASLANE (CLYDE)", lat: 56.07, lon: -4.82, country: "UK", region: "uk", type: "base", pop: 0 },
  // === NATO — WEST GERMANY ===
  { name: "RAMMSTEIN AB", lat: 49.44, lon: 7.60, country: "W.GERMANY", region: "nato", type: "base", pop: 0 },
  { name: "BITBURG AB", lat: 49.95, lon: 6.57, country: "W.GERMANY", region: "nato", type: "base", pop: 0 },
  { name: "SPANGDAHLEM AB", lat: 49.97, lon: 6.69, country: "W.GERMANY", region: "nato", type: "base", pop: 0 },
  { name: "HAHN AB", lat: 49.95, lon: 7.26, country: "W.GERMANY", region: "nato", type: "base", pop: 0 },
  { name: "SEMBACH AB", lat: 49.51, lon: 7.87, country: "W.GERMANY", region: "nato", type: "base", pop: 0 },
  { name: "FULDA GAP", lat: 50.55, lon: 9.68, country: "W.GERMANY", region: "nato", type: "base", pop: 0 },
  // === NATO — OTHER EUROPE ===
  { name: "KEFLAVIK NAS", lat: 63.97, lon: -22.61, country: "ICELAND", region: "nato", type: "base", pop: 0 },
  { name: "AVIANO AB", lat: 46.03, lon: 12.60, country: "ITALY", region: "italian", type: "base", pop: 0 },
  { name: "SIGONELLA NAS", lat: 37.40, lon: 14.92, country: "ITALY", region: "italian", type: "base", pop: 0 },
  { name: "INCIRLIK AB", lat: 37.00, lon: 35.43, country: "TURKEY", region: "turkish", type: "base", pop: 0 },
  { name: "ROTA NS", lat: 36.64, lon: -6.35, country: "SPAIN", region: "nato", type: "base", pop: 0 },
  { name: "SOUDA BAY", lat: 35.49, lon: 24.12, country: "GREECE", region: "nato", type: "base", pop: 0 },
  { name: "LAJES FIELD", lat: 38.76, lon: -27.09, country: "PORTUGAL", region: "nato", type: "base", pop: 0 },
  // === NATO — PACIFIC / ASIA ===
  { name: "YOKOTA AB", lat: 35.75, lon: 139.35, country: "JAPAN", region: "fareast", type: "base", pop: 0 },
  { name: "KADENA AB", lat: 26.35, lon: 127.77, country: "JAPAN", region: "fareast", type: "base", pop: 0 },
  { name: "MISAWA AB", lat: 40.70, lon: 141.37, country: "JAPAN", region: "fareast", type: "base", pop: 0 },
  { name: "OSAN AB", lat: 37.09, lon: 127.03, country: "S.KOREA", region: "fareast", type: "base", pop: 0 },
  { name: "KUNSAN AB", lat: 35.90, lon: 126.62, country: "S.KOREA", region: "fareast", type: "base", pop: 0 },
  { name: "CLARK AB", lat: 15.19, lon: 120.56, country: "PHILIPPINES", region: "seato", type: "base", pop: 0 },
  { name: "SUBIC BAY", lat: 14.79, lon: 120.27, country: "PHILIPPINES", region: "seato", type: "base", pop: 0 },
  { name: "DIEGO GARCIA", lat: -7.32, lon: 72.42, country: "UK", region: "uk", type: "base", pop: 0 },
  // === USSR — STRATEGIC COMMAND ===
  { name: "MOSCOW PVO HQ", lat: 55.75, lon: 37.62, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "KALININGRAD HQ", lat: 54.71, lon: 20.50, country: "USSR", region: "ussr", type: "base", pop: 0 },
  // === USSR — ICBM FIELDS ===
  { name: "KOZELSK (SS-19)", lat: 54.04, lon: 36.01, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "TATISHCHEVO (SS-19)", lat: 51.72, lon: 45.29, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "DOMBAROVSKY (SS-18)", lat: 50.75, lon: 59.53, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "KARTALY (SS-18)", lat: 53.05, lon: 60.65, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "ALEYSK (SS-18)", lat: 52.50, lon: 82.78, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "UZHUR (SS-18)", lat: 55.31, lon: 89.83, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "GLADKAYA (SS-18)", lat: 53.80, lon: 92.87, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "PERVOMAYSK (SS-19)", lat: 48.04, lon: 30.87, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "DERAZHNYA (SS-20)", lat: 49.26, lon: 27.43, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "YOSHKAR-OLA (SS-13)", lat: 56.63, lon: 47.87, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "TEYKOVO (SS-25)", lat: 56.86, lon: 40.54, country: "USSR", region: "ussr", type: "base", pop: 0 },
  // === USSR — STRATEGIC BOMBER BASES ===
  { name: "ENGELS AB", lat: 51.48, lon: 46.20, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "UKRAINKA AB", lat: 51.17, lon: 128.40, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "MOZDOK AB", lat: 43.79, lon: 44.59, country: "USSR", region: "ussr", type: "base", pop: 0 },
  // === USSR — SUBMARINE BASES ===
  { name: "POLYARNY (NORTH FLEET)", lat: 69.20, lon: 33.47, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "GADZHIYEVO", lat: 69.25, lon: 33.32, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "SEVERODVINSK", lat: 64.57, lon: 39.85, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "PETROPAVLOVSK-K", lat: 53.01, lon: 158.65, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "VLADIVOSTOK NB", lat: 43.12, lon: 131.90, country: "USSR", region: "ussr", type: "base", pop: 0 },
  // === USSR — AIR DEFENSE / EARLY WARNING ===
  { name: "SARY SHAGAN", lat: 46.00, lon: 73.60, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "BAIKONUR COSMODROME", lat: 45.97, lon: 63.31, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "PLESETSK COSMODROME", lat: 62.93, lon: 40.58, country: "USSR", region: "ussr", type: "base", pop: 0 },
  { name: "PECHORA RADAR", lat: 65.20, lon: 57.35, country: "USSR", region: "ussr", type: "base", pop: 0 },
  // === USSR — FORWARD DEPLOYED (WARSAW PACT) ===
  { name: "WUNSDORF (GSFG HQ)", lat: 52.17, lon: 13.47, country: "E.GERMANY", region: "pact", type: "base", pop: 0 },
  { name: "ZOSSEN-WUNSDORF", lat: 52.17, lon: 13.47, country: "E.GERMANY", region: "pact", type: "base", pop: 0 },
  { name: "MILOVICE", lat: 50.23, lon: 14.89, country: "CZECHOSLOVAKIA", region: "pact", type: "base", pop: 0 },
  { name: "LEGNICA (NORTHERN GROUP)", lat: 51.21, lon: 16.16, country: "POLAND", region: "pact", type: "base", pop: 0 },
  // === FRANCE — FORCE DE FRAPPE ===
  { name: "ILE LONGUE (SSBN)", lat: 48.31, lon: -4.51, country: "FRANCE", region: "france", type: "base", pop: 0 },
  { name: "PLATEAU D'ALBION", lat: 44.10, lon: 5.52, country: "FRANCE", region: "france", type: "base", pop: 0 },
  // === CHINA ===
  { name: "JIANSHUI (DF-4)", lat: 23.63, lon: 102.83, country: "CHINA", region: "china", type: "base", pop: 0 },
  { name: "DATONG (DF-5)", lat: 40.08, lon: 113.30, country: "CHINA", region: "china", type: "base", pop: 0 },
  { name: "LUOYANG (DF-5)", lat: 34.68, lon: 112.45, country: "CHINA", region: "china", type: "base", pop: 0 },
  { name: "XINING (DF-4)", lat: 36.62, lon: 101.77, country: "CHINA", region: "china", type: "base", pop: 0 },
  { name: "LOP NOR (TEST SITE)", lat: 41.73, lon: 88.33, country: "CHINA", region: "china", type: "base", pop: 0 },
];

// Number of core (non-base) cities — used by switchEra to swap bases
const _CORE_CITY_COUNT = CITIES.length;

// Merge initial era bases into CITIES
for (const base of MILITARY_BASES_1957) {
  CITIES.push(base);
}

// Assign pulse phase offsets so dots twinkle independently
CITIES.forEach((c, i) => {
  c.pulsePhase = i * 0.5;
});

// SSBN patrol positions — era-specific
const SSBN_PATROLS_1957 = {
  us: [
    { name: "SSG PACIFIC-1", lat: 45.0, lon: -155.0, nation: "us" },
    { name: "SSG PACIFIC-2", lat: 38.0, lon: -170.0, nation: "us" },
  ],
  ussr: [
    { name: "SSB BARENTS-1", lat: 72.0, lon: 35.0, nation: "ussr" },
    { name: "SSB BARENTS-2", lat: 70.0, lon: 28.0, nation: "ussr" },
  ],
  uk: [],
  france: [],
  china: [],
};

const SSBN_PATROLS_1983 = {
  us: [
    { name: "SSBN ATLANTIC-1", lat: 52.0, lon: -30.0, nation: "us" },
    { name: "SSBN ATLANTIC-2", lat: 48.0, lon: -22.0, nation: "us" },
    { name: "SSBN ATLANTIC-3", lat: 38.0, lon: -55.0, nation: "us" },
    { name: "SSBN ATLANTIC-4", lat: 42.0, lon: -40.0, nation: "us" },
    { name: "SSBN ATLANTIC-5", lat: 35.0, lon: -65.0, nation: "us" },
    { name: "SSBN PACIFIC-1", lat: 45.0, lon: -155.0, nation: "us" },
    { name: "SSBN PACIFIC-2", lat: 38.0, lon: -170.0, nation: "us" },
    { name: "SSBN PACIFIC-3", lat: 30.0, lon: -145.0, nation: "us" },
    { name: "SSBN PACIFIC-4", lat: 50.0, lon: -165.0, nation: "us" },
    { name: "SSBN ARCTIC-US", lat: 68.0, lon: -10.0, nation: "us" },
  ],
  ussr: [
    { name: "SSBN BARENTS-1", lat: 72.0, lon: 35.0, nation: "ussr" },
    { name: "SSBN BARENTS-2", lat: 74.0, lon: 40.0, nation: "ussr" },
    { name: "SSBN BARENTS-3", lat: 70.0, lon: 28.0, nation: "ussr" },
    { name: "SSBN WHITE SEA", lat: 66.0, lon: 38.0, nation: "ussr" },
    { name: "SSBN ARCTIC-1", lat: 78.0, lon: 45.0, nation: "ussr" },
    { name: "SSBN ARCTIC-2", lat: 76.0, lon: 55.0, nation: "ussr" },
    { name: "SSBN OKHOTSK-1", lat: 54.0, lon: 150.0, nation: "ussr" },
    { name: "SSBN OKHOTSK-2", lat: 50.0, lon: 148.0, nation: "ussr" },
    { name: "SSBN OKHOTSK-3", lat: 56.0, lon: 145.0, nation: "ussr" },
    { name: "SSBN N.ATLANTIC", lat: 62.0, lon: -15.0, nation: "ussr" },
    { name: "SSBN MED", lat: 35.0, lon: 18.0, nation: "ussr" },
  ],
  uk: [
    { name: "SSBN UK-ATLANTIC-1", lat: 58.0, lon: -15.0, nation: "uk" },
    { name: "SSBN UK-ATLANTIC-2", lat: 55.0, lon: -20.0, nation: "uk" },
  ],
  france: [
    { name: "SSBN FR-ATLANTIC-1", lat: 46.0, lon: -10.0, nation: "france" },
    { name: "SSBN FR-ATLANTIC-2", lat: 50.0, lon: -12.0, nation: "france" },
  ],
  china: [
    { name: "SSBN PRC-1", lat: 18.0, lon: 112.0, nation: "china" },
  ],
};

// Active SSBN patrols — swapped by switchEra()
let SSBN_PATROLS = SSBN_PATROLS_1957;

// Determine how many subs each nation deploys based on DEFCON / scenario intensity
function assignSubmarines(regions, defcon) {
  const subs = [];
  const used = new Set();

  function pick(pool, count) {
    const shuffled = pool.filter(s => !used.has(s.name)).sort(() => Math.random() - 0.5);
    const picked = shuffled.slice(0, count);
    picked.forEach(s => { used.add(s.name); subs.push(s); });
    return picked;
  }

  const intensity = Math.max(1, 6 - defcon);

  if (regions.some(r => ["us", "nato", "uk", "alaska", "hawaii"].includes(r))) {
    pick(SSBN_PATROLS.us, Math.min(2 + intensity, 8));
  }
  if (regions.some(r => ["ussr", "pact"].includes(r))) {
    pick(SSBN_PATROLS.ussr, Math.min(2 + intensity, 9));
  }
  if (regions.some(r => ["uk", "nato"].includes(r))) {
    pick(SSBN_PATROLS.uk, Math.min(1, intensity));
  }
  if (regions.some(r => ["france", "nato"].includes(r))) {
    pick(SSBN_PATROLS.france, Math.min(1, intensity));
  }
  if (regions.some(r => r === "china") && defcon <= 2) {
    pick(SSBN_PATROLS.china, 1);
  }

  return subs;
}

// Region keyword mapping for scenario name parsing
const REGION_KEYWORDS = {
  "U.S.": ["us"],
  "USSR": ["ussr"],
  "NATO": ["nato", "us", "english", "french", "italian", "danish", "turkish"],
  "WARSAW PACT": ["pact", "ussr", "czech", "romanian", "bulgarian", "albanian"],
  "PACT": ["pact", "ussr", "czech", "romanian", "bulgarian"],
  "FAR EAST": ["fareast", "china", "hongkong", "taiwan"],
  "MIDDLE EAST": ["israel", "syrian", "lebanon", "iraq", "iranian", "saudi", "egypt"],
  "SEATO": ["seato", "thai", "malaysian", "australian"],
  "ATLANTIC": ["us", "english", "iceland", "nato"],
  "PACIFIC": ["us", "fareast", "australian", "hawaiian"],
  "ARCTIC": ["arctic", "ussr", "alaska", "greenland"],
  "NORTHERN": ["ussr", "arctic", "iceland", "greenland"],
  "MEDITERRANEAN": ["italian", "turkish", "egyptian", "libyan", "syrian"],
  "AFRICAN": ["sudan", "zaire", "chad", "ethiopian", "kenya", "uganda", "s.african", "gabon"],
  "ASIAN": ["china", "fareast", "vietnamese", "thai", "burmese", "cambodian"],
  "CUBAN": ["cuba"],
  "NICARAGUAN": ["nicaragua"],
  "BURMESE": ["burmese"],
  "TURKISH": ["turkish"],
  "ARGENTINA": ["argentina"],
  "ANGENTINA": ["argentina"],
  "ICELAND": ["iceland"],
  "ARABIAN": ["saudi", "iraqi", "iranian"],
  "AUSTRALIAN": ["australian"],
  "SUDAN": ["sudan"],
  "ZAIRE": ["zaire"],
  "ENGLISH": ["english"],
  "MEXICAN": ["mexico"],
  "CHAD": ["chad"],
  "SAUDI": ["saudi"],
  "ETHIOPIAN": ["ethiopian"],
  "CAMBODIAN": ["cambodian"],
  "TAIWAN": ["taiwan"],
  "PORTUGAL": ["portugal"],
  "ALBANIAN": ["albanian"],
  "PALESTINIAN": ["israel", "syrian", "lebanon"],
  "PALISTINIAN": ["israel", "syrian", "lebanon"],
  "MOROCCAN": ["moroccan"],
  "BAVARIAN": ["bavarian"],
  "CZECH": ["czech"],
  "FRENCH": ["french"],
  "GABON": ["gabon"],
  "DANISH": ["danish"],
  "HAWAIIAN": ["hawaii", "us"],
  "IRANIAN": ["iranian"],
  "SWISS": ["swiss"],
  "VIETNAMESE": ["vietnamese"],
  "SYRIAN": ["syrian"],
  "LIBYAN": ["libyan"],
  "ROMANIAN": ["romanian"],
  "DENMARK": ["danish"],
  "CHILE": ["chile"],
  "S.AFRICAN": ["s.african"],
  "INDIA": ["india"],
  "PAKISTAN": ["pakistan"],
  "HONGKONG": ["hongkong"],
  "CHINA": ["china"],
  "AFGHAN": ["afghan"],
  "ITALIAN": ["italian"],
  "BRAZILIAN": ["brazilian"],
  "VENEZUELA": ["venezuela"],
  "MAYLASIAN": ["malaysian"],
  "MALAYSIAN": ["malaysian"],
  "ISREAL": ["israel"],
  "ISRAEL": ["israel"],
  "CYPRESS": ["cyprus"],
  "CYPRUS": ["cyprus"],
  "EGYPT": ["egypt"],
  "BANGLADESH": ["bangladesh"],
  "KENYA": ["kenya"],
  "IRAQ": ["iraq"],
  "LEBANON": ["lebanon"],
  "ALGERIAN": ["algerian"],
  "MONGOLIAN": ["mongolian"],
  "POLISH": ["pact"],
  "ALASKAN": ["alaska"],
  "CANADIAN": ["canada"],
  "TUNISIAN": ["tunisian"],
  "JAMAICA": ["jamaica"],
  "RUSSIAN": ["ussr"],
  "BURMESE": ["burmese"],
  "BULGARIAN": ["bulgarian"],
  "GREENLAND": ["greenland"],
  "CASPIAN": ["caspian"],
  "UGANDA": ["uganda"],
};

// Escalation type keywords that affect DEFCON level
const ESCALATION_KEYWORDS = {
  5: ["MINIMAL", "LOCAL", "INCIDENT", "DOMESTIC", "LIGHT", "DECOY", "DISCRETIONARY", "ALERT", "OPTION", "CLANDESTINE"],
  4: ["MANEUVER", "DEFENSE", "CONTAINMENT", "SUBVERSION", "CONFRONTATION", "PARAMILITARY", "MISDIRECTION", "INTERDICTION", "ALTERNATE"],
  3: ["PROVOCATION", "ESCALATION", "REBELLION", "REVOLUTION", "TACTICAL", "SURGICAL", "TERRITORIAL"],
  2: ["STRIKE", "HEAVY", "OFFENSIVE", "THEATERWIDE", "TAKEOVER", "SUDDEN", "SURPRISE", "THRUST", "PREEMPTIVE", "MAXIMUM", "MASSIVE", "SOVEREIGNTY", "RETALIATION", "ACTION"],
  1: ["FIRST STRIKE", "DECAPITATING", "WAR"]
};

// Embedded fallback for file:// protocol (fetch won't work)
const EMBEDDED_SCENARIOS_1957 = [
  "SAC FIRST STRIKE","SOVIET FIRST STRIKE","NATO MASSIVE RETALIATION",
  "FULDA GAP BREAKTHROUGH","BERLIN CRISIS","BOMBER GAP SURPRISE",
  "SUEZ ESCALATION","ARCTIC OVERWATCH","TURKISH STRAITS CRISIS",
  "KOREAN FLASHPOINT"
];

const EMBEDDED_SCENARIOS_1983 = [
  "U.S. FIRST STRIKE","USSR FIRST STRIKE","NATO / WARSAW PACT","FAR EAST STRATEGY",
  "US USSR ESCALATION","MIDDLE EAST WAR","USSR CHINA ATTACK","INDIA PAKISTAN WAR",
  "MEDITERRANEAN WAR","HONGKONG VARIANT","SEATO DECAPITATING","CUBAN PROVOCATION",
  "ATLANTIC HEAVY","CUBAN PARAMILITARY","NICARAGUAN PREEMPTIVE","PACIFIC TERRITORIAL",
  "BURMESE THEATERWIDE","TURKISH DECOY","ARGENTINA ESCALATION","ICELAND MAXIMUM",
  "ARABIAN THEATERWIDE","U.S. SUBVERSION","AUSTRALIAN MANEUVER","SUDAN SURPRISE",
  "NATO TERRITORIAL","ZAIRE ALLIANCE","ICELAND INCIDENT","ENGLISH ESCALATION",
  "MIDDLE EAST HEAVY","MEXICAN TAKEOVER","CHAD ALERT","SAUDI MANEUVER",
  "AFRICAN TERRITORIAL","ETHIOPIAN ESCALATION","TURKISH HEAVY","NATO INCURSION",
  "U.S. DEFENSE","CAMBODIAN HEAVY","PACT MEDIUM","ARCTIC MINIMAL",
  "MEXICAN DOMESTIC","TAIWAN THEATERWIDE","PACIFIC MANEUVER","PORTUGAL REVOLUTION",
  "ALBANIAN DECOY","PALESTINIAN LOCAL","MOROCCAN MINIMAL","BAVARIAN DIVERSITY",
  "CZECH OPTION","FRENCH ALLIANCE","ARABIAN CLANDESTINE","GABON REBELLION",
  "NORTHERN MAXIMUM","DANISH PARAMILITARY","SEATO TAKEOVER","HAWAIIAN ESCALATION",
  "IRANIAN MANEUVER","NATO CONTAINMENT","SWISS INCIDENT","CUBAN MINIMAL",
  "CHAD ALERT","ICELAND ESCALATION","VIETNAMESE RETALIATION","SYRIAN PROVOCATION",
  "LIBYAN LOCAL","GABON TAKEOVER","ROMANIAN WAR","MIDDLE EAST OFFENSIVE",
  "DENMARK MASSIVE","CHILE CONFRONTATION","S.AFRICAN SUBVERSION","USSR ALERT",
  "NICARAGUAN THRUST","GREENLAND DOMESTIC","ICELAND HEAVY","KENYA OPTION",
  "PACIFIC DEFENSE","UGANDA MAXIMUM","THAI SUBVERSION","ROMANIAN STRIKE",
  "PAKISTAN SOVEREIGNTY","AFGHAN MISDIRECTION","ETHIOPIAN LOCAL","ITALIAN TAKEOVER",
  "VIETNAMESE INCIDENT","ENGLISH PREEMPTIVE","DENMARK ALTERNATE","THAI CONFRONTATION",
  "TAIWAN SURPRISE","BRAZILIAN STRIKE","VENEZUELA SUDDEN","MALAYSIAN ALERT",
  "ISRAEL DISCRETIONARY","LIBYAN ACTION","PALESTINIAN TACTICAL","NATO ALTERNATE",
  "CYPRUS MANEUVER","EGYPT MISDIRECTION","BANGLADESH THRUST","KENYA DEFENSE",
  "BANGLADESH CONTAINMENT","VIETNAMESE STRIKE","ALBANIAN CONTAINMENT","GABON SURPRISE",
  "IRAQ SOVEREIGNTY","VIETNAMESE SUDDEN","LEBANON INTERDICTION","TAIWAN DOMESTIC",
  "ALGERIAN SOVEREIGNTY","ARABIAN STRIKE","ATLANTIC SUDDEN","MONGOLIAN THRUST",
  "POLISH DECOY","ALASKAN DISCRETIONARY","CANADIAN THRUST","ARABIAN LIGHT",
  "S.AFRICAN DOMESTIC","TUNISIAN INCIDENT","MALAYSIAN MANEUVER","JAMAICA DECOY",
  "MALAYSIAN MINIMAL","RUSSIAN SOVEREIGNTY","CHAD OPTION","BANGLADESH WAR",
  "BURMESE CONTAINMENT","ASIAN THEATERWIDE","BULGARIAN CLANDESTINE","GREENLAND INCURSION",
  "EGYPT SURGICAL","CZECH HEAVY","TAIWAN CONFRONTATION","GREENLAND MAXIMUM",
  "UGANDA OFFENSIVE","CASPIAN DEFENSE"
];

let EMBEDDED_SCENARIOS = EMBEDDED_SCENARIOS_1957;

// Switch all era-specific data
function switchEra(era) {
  CURRENT_ERA = era;

  // Swap bases in CITIES array
  CITIES.length = _CORE_CITY_COUNT;
  const bases = era === '1957' ? MILITARY_BASES_1957 : MILITARY_BASES_1983;
  for (const base of bases) {
    CITIES.push(base);
  }
  // Re-assign pulse phases
  CITIES.forEach((c, i) => { c.pulsePhase = i * 0.5; });

  // Swap SSBNs
  SSBN_PATROLS = era === '1957' ? SSBN_PATROLS_1957 : SSBN_PATROLS_1983;

  // Swap scenarios
  EMBEDDED_SCENARIOS = era === '1957' ? EMBEDDED_SCENARIOS_1957 : EMBEDDED_SCENARIOS_1983;
  switchScenarios(era);
}
