// City database and region mappings for WOPR globe
// (Continent outlines are in coastlines.js)

// Major world cities for targeting
const CITIES = [
  { name: "LONDON", lat: 51.5, lon: -0.1, country: "UK", region: "english" },
  { name: "MOSCOW", lat: 55.8, lon: 37.6, country: "USSR", region: "ussr" },
  { name: "WASHINGTON DC", lat: 38.9, lon: -77.0, country: "US", region: "us" },
  { name: "MIAMI", lat: 25.8, lon: -80.2, country: "US", region: "us" },
  { name: "LOS ANGELES", lat: 34.1, lon: -118.2, country: "US", region: "us" },
  { name: "PARIS", lat: 48.9, lon: 2.3, country: "FRANCE", region: "french" },
  { name: "SYDNEY", lat: -33.9, lon: 151.2, country: "AUSTRALIA", region: "australian" },
];

// Region keyword mapping for strategy name parsing
const REGION_KEYWORDS = {
  "U.S.": ["us"],
  "USSR": ["ussr"],
  "NATO": ["nato", "us", "english", "french", "italian", "danish", "turkish"],
  "WARSAW PACT": ["pact", "ussr", "czech", "romanian", "bulgarian", "albanian"],
  "PACT": ["pact", "ussr", "czech", "romanian", "bulgarian"],
  "FAR EAST": ["fareast", "china", "hongkong", "taiwan"],
  "MIDDLE EAST": ["isreal", "syrian", "lebanon", "iraq", "iranian", "saudi", "egypt"],
  "SEATO": ["seato", "thai", "malaysian", "australian"],
  "ATLANTIC": ["us", "english", "iceland", "nato"],
  "PACIFIC": ["us", "fareast", "australian", "hawaiian"],
  "ARCTIC": ["arctic", "ussr", "alaska", "greenland"],
  "NORTHERN": ["ussr", "arctic", "iceland", "greenland"],
  "MEDITERRANEAN": ["italian", "turkish", "egyptian", "libyan", "syrian"],
  "AFRICAN": ["sudan", "zaire", "chad", "ethiopian", "kenya", "uganda", "s.african", "gabon"],
  "ASIAN": ["china", "fareast", "vietnamese", "thai", "burmese", "cambodian"],
  "CUBAN": ["cuba"],
  "NICARAGUAN": ["nicaragua"],
  "BURMESE": ["burmese"],
  "TURKISH": ["turkish"],
  "ARGENTINA": ["argentina"],
  "ANGENTINA": ["argentina"],
  "ICELAND": ["iceland"],
  "ARABIAN": ["saudi", "iraqi", "iranian"],
  "AUSTRALIAN": ["australian"],
  "SUDAN": ["sudan"],
  "ZAIRE": ["zaire"],
  "ENGLISH": ["english"],
  "MEXICAN": ["mexico"],
  "CHAD": ["chad"],
  "SAUDI": ["saudi"],
  "ETHIOPIAN": ["ethiopian"],
  "CAMBODIAN": ["cambodian"],
  "TAIWAN": ["taiwan"],
  "PORTUGAL": ["portugal"],
  "ALBANIAN": ["albanian"],
  "PALESTINIAN": ["isreal", "syrian", "lebanon"],
  "PALISTINIAN": ["isreal", "syrian", "lebanon"],
  "MOROCCAN": ["moroccan"],
  "BAVARIAN": ["bavarian"],
  "CZECH": ["czech"],
  "FRENCH": ["french"],
  "GABON": ["gabon"],
  "DANISH": ["danish"],
  "HAWAIIAN": ["hawaii", "us"],
  "IRANIAN": ["iranian"],
  "SWISS": ["swiss"],
  "VIETNAMESE": ["vietnamese"],
  "SYRIAN": ["syrian"],
  "LIBYAN": ["libyan"],
  "ROMANIAN": ["romanian"],
  "DENMARK": ["danish"],
  "CHILE": ["chile"],
  "S.AFRICAN": ["s.african"],
  "INDIA": ["india"],
  "PAKISTAN": ["pakistan"],
  "HONGKONG": ["hongkong"],
  "CHINA": ["china"],
  "AFGHAN": ["afghan"],
  "ITALIAN": ["italian"],
  "BRAZILIAN": ["brazilian"],
  "VENEZUELA": ["venezuela"],
  "MAYLASIAN": ["malaysian"],
  "MALAYSIAN": ["malaysian"],
  "ISREAL": ["isreal"],
  "CYPRESS": ["cypress"],
  "EGYPT": ["egypt"],
  "BANGLADESH": ["bangladesh"],
  "KENYA": ["kenya"],
  "IRAQ": ["iraq"],
  "LEBANON": ["lebanon"],
  "ALGERIAN": ["algerian"],
  "MONGOLIAN": ["mongolian"],
  "POLISH": ["pact"],
  "ALASKAN": ["alaska"],
  "CANADIAN": ["canada"],
  "TUNISIAN": ["tunisian"],
  "JAMAICA": ["jamaica"],
  "RUSSIAN": ["ussr"],
  "BURMESE": ["burmese"],
  "BULGARIAN": ["bulgarian"],
  "GREENLAND": ["greenland"],
  "CASPIAN": ["caspian"],
  "UGANDA": ["uganda"],
};

// Escalation type keywords that affect DEFCON level
const ESCALATION_KEYWORDS = {
  5: ["MINIMAL", "LOCAL", "INCIDENT", "DOMESTIC", "LIGHT", "DECOY", "DISCRETIONARY", "ALERT", "OPTION", "CLANDESTINE"],
  4: ["MANEUVER", "DEFENSE", "CONTAINMENT", "SUBVERSION", "CONFRONTATION", "PARAMILITARY", "MISDIRECTION", "INTERDICTION", "ALTERNATE"],
  3: ["PROVOCATION", "ESCALATION", "REBELLION", "REVOLUTION", "TACTICAL", "SURGICAL", "TERRITORIAL"],
  2: ["STRIKE", "HEAVY", "OFFENSIVE", "THEATERWIDE", "TAKEOVER", "SUDDEN", "SURPRISE", "THRUST", "PREEMPTIVE", "MAXIMUM", "MASSIVE", "SOVEREIGNTY", "RETALIATIO", "ACTION"],
  1: ["FIRST STRIKE", "DECAPITATING", "WAR"]
};

// Embedded fallback for file:// protocol (fetch won't work)
const EMBEDDED_STRATEGIES = [
  "U.S. FIRST STRIKE","USSR FIRST STRIKE","NATO / WARSAW PACT","FAR EAST STRATEGY",
  "US USSR ESCALATION","MIDDLE EAST WAR","USSR CHINA ATTACK","INDIA PAKISTAN WAR",
  "MEDITERRANEAN WAR","HONGKONG VARIANT","SEATO DECAPITATING","CUBAN PROVOCATION",
  "ATLANTIC HEAVY","CUBAN PARAMILITARY","NICARAGUAN PREEMPTIVE","PACIFIC TERRITORIAL",
  "BURMESE THEATERWIDE","TURKISH DECOY","ANGENTINA(SIC) ESCALATION","ICELAND MAXIMUM",
  "ARABIAN THEATERWIDE","U.S. SUBVERSION","AUSTRALIAN MANEUVER","SUDAN SURPRISE",
  "NATO TERRITORIAL","ZAIRE ALLIANCE","ICELAND INCIDENT","ENGLISH ESCALATION",
  "MIDDLE EAST HEAVY","MEXICAN TAKEOVER","CHAD ALERT","SAUDI MANEUVER",
  "AFRICAN TERRITORIAL","ETHIOPIAN ESCALATION","TURKISH HEAVY","NATO INCURSION",
  "U.S. DEFENSE","CAMBODIAN HEAVY","PACT MEDIUM","ARCTIC MINIMAL",
  "MEXICAN DOMESTIC","TAIWAN THEATERWIDE","PACIFIC MANEUVER","PORTUGAL REVOLUTION",
  "ALBANIAN DECOY","PALESTINIAN LOCAL","MOROCCAN MINIMAL","BAVARIAN DIVERSITY",
  "CZECH OPTION","FRENCH ALLIANCE","ARABIAN CLANDESTINE","GABON REBELLION",
  "NORTHERN MAXIMUM","DANISH PARAMILITARY","SEATO TAKEOVER","HAWAIIAN ESCALATION",
  "IRANIAN MANEUVER","NATO CONTAINMENT","SWISS INCIDENT","CUBAN MINIMAL",
  "CHAD ALERT","ICELAND ESCALATION","VIETNAMESE RETALIATIO","SYRIAN PROVOCATION",
  "LIBYAN LOCAL","GABON TAKEOVER","ROMANIAN WAR","MIDDLE EAST OFFENSIVE",
  "DENMARK MASSIVE","CHILE CONFRONTATION","S.AFRICAN SUBVERSION","USSR ALERT",
  "NICARAGUAN THRUST","GREENLAND DOMESTIC","ICELAND HEAVY","KENYA OPTION",
  "PACIFIC DEFENSE","UGANDA MAXIMUM","THAI SUBVERSION","ROMANIAN STRIKE",
  "PAKISTAN SOVEREIGNTY","AFGHAN MISDIRECTION","ETHIOPIAN LOCAL","ITALIAN TAKEOVER",
  "VIETNAMESE INCIDENT","ENGLISH PREEMPTIVE","DENMARK ALTERNATE","THAI CONFRONTATION",
  "TAIWAN SURPRISE","BRAZILIAN STRIKE","VENEZUELA SUDDEN","MAYLASIAN ALERT",
  "ISREAL DISCRETIONARY","LIBYAN ACTION","PALISTINIAN TACTICAL","NATO ALTERNATE",
  "CYPRESS MANEUVER","EGYPT MISDIRECTION","BANGLADESH THRUST","KENYA DEFENSE",
  "BANGLADESH CONTAINMENT","VIETNAMESE STRIKE","ALBANIAN CONTAINMENT","GABON SURPRISE",
  "IRAQ SOVEREIGNTY","VIETNAMESE SUDDEN","LEBANON INTERDICTION","TAIWAN DOMESTIC",
  "ALGERIAN SOVEREIGNTY","ARABIAN STRIKE","ATLANTIC SUDDEN","MONGOLIAN THRUST",
  "POLISH DECOY","ALASKAN DISCRETIONARY","CANADIAN THRUST","ARABIAN LIGHT",
  "S.AFRICAN DOMESTIC","TUNISIAN INCIDENT","MALAYSIAN MANEUVER","JAMAICA DECOY",
  "MALAYSIAN MINIMAL","RUSSIAN SOVEREIGNTY","CHAD OPTION","BANGLADESH WAR",
  "BURMESE CONTAINMENT","ASIAN THEATERWIDE","BULGARIAN CLANDESTINE","GREENLAND INCURSION",
  "EGYPT SURGICAL","CZECH HEAVY","TAIWAN CONFRONTATION","GREENLAND MAXIMUM",
  "UGANDA OFFENSIVE","CASPIAN DEFENSE"
];
